"""Colour groups of the plane: exact enumeration of the coloured 2D crystals.

A k-coloured plane crystal is a pair Gamma > H — a wallpaper group with a
subgroup of index k, the stabiliser of one colour — up to affine equivalence
of pairs (van der Waerden & Burckhardt 1961; Jarratt & Schwarzenberger 1980;
Wieting 1982).  Equivalently: a discrete subgroup of E(2) x S_k with faithful
crystallographic spatial projection, transitive on colours, up to
(affine) x (relabelling) conjugacy.  This module enumerates all of them for
k <= 6, entirely in exact rational arithmetic (pure Python, no dependencies
beyond exact.py), and emits render-ready data for the site.

ANCHOR: the per-group counts must reproduce Table 8.2.1 of Grünbaum &
Shephard, "Tilings and Patterns" (the periodic columns, from Wieting [1981])
= Jarratt & Schwarzenberger's Table 5:

    k:      2   3   4   5   6
    total  46  23  96  14  90     -> 269 coloured crystals in all.

The enumeration also computes, per class: the type of H and of the kernel
(colour-fixing) subgroup, the colour-permutation action, normality,
cyclicity (a clock can drive the colouring), and chirality under
PROPER-affine equivalence (the analogue of the 230-vs-219 distinction of
3D crystallography; the literature convention above allows reflections).

Representation.  Each of the 17 wallpaper groups Gamma is modelled with a
primitive translation lattice T = Z^2: Gamma = { (M | v_M + Z^2) }, point
matrices M in GL(2,Z) written in lattice coordinates, v_M in (1/2)Z^2.
A subgroup H of index k = a*b is the datum (L, Q, w): L = H ∩ T a sublattice
of index a, Q = the point-group image of H of index b in P (Q must preserve
L), and w: Q -> Q^2 a system of translation parts, w_M in v_M + Z^2, with the
cocycle condition w_{MN} ≡ w_M + M w_N (mod L).  Two subgroups give the same
coloured crystal iff they are conjugate under the affine normaliser of Gamma;
since conjugation must preserve T = Z^2, the normaliser is generated by
integer changes of basis A (A P A^{-1} = P, with a compatible translation)
and by translations, and orbits are computed by breadth-first closure.
Continuous normaliser directions satisfy (I - M) t = 0 for every M and act
trivially on the data, so a finite grid of rational translations suffices.
"""

from fractions import Fraction
import itertools
import json
import math
import os

from exact import smith_normal_form

F = Fraction
ZERO = (F(0), F(0))
I2 = ((1, 0), (0, 1))

HERE = os.path.dirname(os.path.abspath(__file__))
DOCS = os.path.join(HERE, "..", "docs")


# ---------------------------------------------------------------- basic 2x2

def mmul(A, B):
    return (
        (A[0][0] * B[0][0] + A[0][1] * B[1][0], A[0][0] * B[0][1] + A[0][1] * B[1][1]),
        (A[1][0] * B[0][0] + A[1][1] * B[1][0], A[1][0] * B[0][1] + A[1][1] * B[1][1]),
    )


def mvec(A, v):
    return (A[0][0] * v[0] + A[0][1] * v[1], A[1][0] * v[0] + A[1][1] * v[1])


def mdet(A):
    return A[0][0] * A[1][1] - A[0][1] * A[1][0]


def minv_uni(A):
    """Inverse of a unimodular integer matrix (det = +-1)."""
    d = mdet(A)
    assert d in (1, -1), A
    return ((d * A[1][1], -d * A[0][1]), (-d * A[1][0], d * A[0][0]))


def vadd(u, v):
    return (u[0] + v[0], u[1] + v[1])


def vsub(u, v):
    return (u[0] - v[0], u[1] - v[1])


def is_int(x):
    return F(x).denominator == 1


def vmod1(v):
    return (F(v[0]) % 1, F(v[1]) % 1)


# ------------------------------------------------- group elements (M | v)

def gmul(a, b):
    """(M|v) (N|w) = (MN | v + M w).  Exact, no reduction."""
    (M, v), (N, w) = a, b
    return (mmul(M, N), vadd(v, mvec(M, w)))


def ginv(a):
    M, v = a
    Mi = minv_uni(M)
    w = mvec(Mi, v)
    return (Mi, (-w[0], -w[1]))


def point_group_from_gens(gens):
    """Close {(M | v mod 1)} under multiplication: the finite quotient
    Gamma/T as a dict M -> v (each matrix once, translation part mod 1)."""
    ops = {I2: ZERO}
    changed = True
    while changed:
        changed = False
        items = list(ops.items())
        for M1, v1 in items:
            for M2, v2 in list(gens) + items:
                M, v = gmul((M1, v1), (M2, v2))
                v = vmod1(v)
                if M not in ops:
                    ops[M] = v
                    changed = True
                else:
                    d = vsub(ops[M], v)
                    assert is_int(d[0]) and is_int(d[1]), \
                        "inconsistent translation parts in point-group closure"
    return ops


# ------------------------------------------------------------- the 17 models

MX = ((1, 0), (0, -1))      # reflection fixing the x-axis
R2 = ((-1, 0), (0, -1))
R4 = ((0, -1), (1, 0))
R3 = ((0, -1), (1, -1))
R6 = ((1, -1), (1, 0))
SW = ((0, 1), (1, 0))
NSW = ((0, -1), (-1, 0))
H2 = F(1, 2)

SQ3 = math.sqrt(3) / 2

BAS_OBL = ((1.0, 0.0), (0.32, 1.06))       # columns b1, b2 (cartesian)
BAS_RECT = ((1.0, 0.0), (0.0, 1.36))
BAS_RHOMB = ((0.5, -0.68), (0.5, 0.68))    # |b1| = |b2|, swap = vertical mirror
BAS_SQ = ((1.0, 0.0), (0.0, 1.0))
BAS_HEX = ((1.0, 0.0), (-0.5, SQ3))

WALLPAPERS = [
    # hm, orbifold, generators [(M, v)], cartesian basis
    ("p1",   "◦",     [],                              BAS_OBL),
    ("p2",   "2222",  [(R2, ZERO)],                    BAS_OBL),
    ("pm",   "**",    [(MX, ZERO)],                    BAS_RECT),
    ("pg",   "××",    [(MX, (H2, F(0)))],              BAS_RECT),
    ("cm",   "*×",    [(SW, ZERO)],                    BAS_RHOMB),
    ("pmm",  "*2222", [(R2, ZERO), (MX, ZERO)],        BAS_RECT),
    ("pmg",  "22*",   [(R2, ZERO), (MX, (H2, F(0)))],  BAS_RECT),
    ("pgg",  "22×",   [(R2, ZERO), (MX, (H2, H2))],    BAS_RECT),
    ("cmm",  "2*22",  [(R2, ZERO), (SW, ZERO)],        BAS_RHOMB),
    ("p4",   "442",   [(R4, ZERO)],                    BAS_SQ),
    ("p4m",  "*442",  [(R4, ZERO), (SW, ZERO)],        BAS_SQ),
    ("p4g",  "4*2",   [(R4, ZERO), (MX, (H2, H2))],    BAS_SQ),
    ("p3",   "333",   [(R3, ZERO)],                    BAS_HEX),
    ("p3m1", "*333",  [(R3, ZERO), (NSW, ZERO)],       BAS_HEX),
    ("p31m", "3*3",   [(R3, ZERO), (SW, ZERO)],        BAS_HEX),
    ("p6",   "632",   [(R6, ZERO)],                    BAS_HEX),
    ("p6m",  "*632",  [(R6, ZERO), (SW, ZERO)],        BAS_HEX),
]

EXPECT_ORDER = {"p1": 1, "p2": 2, "pm": 2, "pg": 2, "cm": 2, "pmm": 4,
                "pmg": 4, "pgg": 4, "cmm": 4, "p4": 4, "p4m": 8, "p4g": 8,
                "p3": 3, "p3m1": 6, "p31m": 6, "p6": 6, "p6m": 12}

# Grünbaum & Shephard, Tilings and Patterns, Table 8.2.1 (periodic rows,
# from Wieting [1981]; identical to Jarratt & Schwarzenberger's Table 5).
TABLE_8_2_1 = {
    #        k=2  3   4  5   6
    "p1":   (1, 1, 2, 1, 1),
    "pg":   (2, 2, 4, 2, 5),
    "pm":   (5, 2, 10, 2, 11),
    "cm":   (3, 2, 7, 2, 7),
    "p2":   (2, 1, 3, 1, 2),
    "pgg":  (2, 1, 4, 1, 4),
    "pmg":  (5, 2, 11, 2, 11),
    "pmm":  (5, 1, 13, 1, 9),
    "cmm":  (5, 1, 11, 1, 8),
    "p3":   (0, 2, 1, 0, 1),
    "p31m": (1, 2, 1, 0, 5),
    "p3m1": (1, 2, 1, 0, 4),
    "p4":   (2, 0, 5, 1, 2),
    "p4g":  (3, 0, 7, 0, 2),
    "p4m":  (5, 0, 13, 0, 2),
    "p6":   (1, 2, 1, 0, 5),
    "p6m":  (3, 2, 2, 0, 11),
}
TABLE_TOTALS = (46, 23, 96, 14, 90)


class Wallpaper:
    def __init__(self, hm, orb, gens, basis):
        self.hm = hm
        self.orb = orb
        self.gens = gens
        self.basis = basis
        self.ops = point_group_from_gens(gens)          # M -> v (mod 1)
        assert len(self.ops) == EXPECT_ORDER[hm], (hm, len(self.ops))
        # generators of the full group Gamma (exact, unreduced)
        self.full_gens = [(I2, (F(1), F(0))), (I2, (F(0), F(1)))] + \
                         [(M, v) for M, v in gens]
        # conjugation-invariant fingerprint of the point-matrix set
        self.finger = tuple(sorted((mdet(M), M[0][0] + M[1][1])
                                   for M in self.ops))


GROUPS = {hm: Wallpaper(hm, orb, gens, basis) for hm, orb, gens, basis in WALLPAPERS}
ORDER17 = [w[0] for w in WALLPAPERS]


# --------------------------------------------------------------- sublattices

def divisors(n):
    return [d for d in range(1, n + 1) if n % d == 0]


def sublattices(a):
    """All sublattices of Z^2 of index a, as HNF matrices ((d1, c), (0, d2)):
    columns b1 = (d1, 0), b2 = (c, d2), with d1*d2 = a, 0 <= c < d1."""
    out = []
    for d1 in divisors(a):
        d2 = a // d1
        for c in range(d1):
            out.append(((d1, c), (0, d2)))
    return out


def in_lat(v, B):
    """Is the rational vector v in the lattice with HNF matrix B?"""
    d1, c = B[0]
    d2 = B[1][1]
    j = F(v[1]) / d2
    if j.denominator != 1:
        return False
    i = (F(v[0]) - c * j) / d1
    return i.denominator == 1


def lat_cols(B):
    return ((B[0][0], B[1][0]), (B[0][1], B[1][1]))   # b1, b2


def lat_index(B):
    return B[0][0] * B[1][1]


def hnf_of(vectors):
    """HNF ((d1,c),(0,d2)) of the lattice generated by integer vectors
    (must have rank 2)."""
    vs = [(int(v[0]), int(v[1])) for v in vectors if v != (0, 0)]
    # euclidean reduction on the second coordinate
    while True:
        nz = [v for v in vs if v[1] != 0]
        if len(nz) <= 1:
            break
        piv = min(nz, key=lambda v: abs(v[1]))
        out = []
        for v in vs:
            if v is piv or v[1] == 0:
                if v is not piv:
                    out.append(v)
                continue
            q = v[1] // piv[1]
            out.append((v[0] - q * piv[0], v[1] - q * piv[1]))
        vs = out + [piv]
    piv = [v for v in vs if v[1] != 0]
    assert piv, ("rank < 2", vectors)
    piv = piv[0]
    if piv[1] < 0:
        piv = (-piv[0], -piv[1])
    xs = [abs(v[0]) for v in vs if v[1] == 0 and v[0] != 0]
    assert xs, ("rank < 2", vectors)
    d1 = 0
    for x in xs:
        d1 = math.gcd(d1, x)
    d2 = piv[1]
    c = piv[0] % d1
    return ((d1, c), (0, d2))


def wred(w, B):
    """Canonical representative of the rational vector w modulo the lattice B:
    fractional parts kept, integer part reduced into the HNF box."""
    fx, fy = F(w[0]) % 1, F(w[1]) % 1
    nx, ny = int(w[0] - fx), int(w[1] - fy)
    d1, c = B[0]
    d2 = B[1][1]
    j = ny // d2
    nx, ny = nx - j * c, ny - j * d2
    i = nx // d1
    nx = nx - i * d1
    return (nx + fx, ny + fy)


def lat_box(B):
    """Coset representatives of Z^2 / B."""
    d1 = B[0][0]
    d2 = B[1][1]
    return [(F(i), F(j)) for i in range(d1) for j in range(d2)]


# ------------------------------------------------ exact congruence solving

def solve_cong(pairs):
    """Solve the system  IM_r · t ≡ rhs_r (mod Z^2), r = 1..m,  for t in Q^2.
    pairs = [(IM, rhs)] with IM integer 2x2, rhs rational 2-vector.
    Returns a particular rational solution t, or None if unsolvable.
    (Continuous solution directions exist when the stacked matrix has rank
    < 2; they are irrelevant for existence and a rational particular
    solution is always produced when solvable.)"""
    R = []
    r = []
    for IM, rhs in pairs:
        R.append([IM[0][0], IM[0][1]])
        R.append([IM[1][0], IM[1][1]])
        r.append(F(rhs[0]))
        r.append(F(rhs[1]))
    m = len(R)
    if m == 0:
        return ZERO
    D, U, V = smith_normal_form([row[:] for row in R])
    Ur = [sum(F(U[i][j]) * r[j] for j in range(m)) for i in range(m)]
    s = [F(0), F(0)]
    for i in range(m):
        d = D[i][0] if i == 0 else (D[i][1] if i == 1 else 0)
        if i < 2 and d != 0:
            s[i] = Ur[i] / d
        else:
            if not is_int(Ur[i]):
                return None
    t = (F(V[0][0]) * s[0] + F(V[0][1]) * s[1],
         F(V[1][0]) * s[0] + F(V[1][1]) * s[1])
    return t


def conj_pairs(G, A, target_ops):
    """The congruence system for (A|t) to conjugate G onto target_ops.
    Returns None if the matrix parts do not match."""
    Ai = minv_uni(A)
    pairs = []
    for M, v in G.items():
        Mp = mmul(mmul(A, M), Ai)
        if Mp not in target_ops:
            return None
        IM = ((1 - Mp[0][0], -Mp[0][1]), (-Mp[1][0], 1 - Mp[1][1]))
        rhs = vsub(target_ops[Mp], mvec(A, v))
        pairs.append((IM, rhs))
    return pairs


# ------------------------------------------------------- subgroup enumeration

def point_subgroups(P):
    """All subgroups of the finite matrix group P (<= 12 elements; all 2D
    point groups are generated by at most 2 elements)."""
    mats = list(P)
    found = {}

    def close(gens):
        S = {I2}
        frontier = [I2]
        while frontier:
            nxt = []
            for A in frontier:
                for g in gens:
                    Bm = mmul(g, A)
                    if Bm not in S:
                        S.add(Bm)
                        nxt.append(Bm)
            frontier = nxt
        return tuple(sorted(S))

    found[close([])] = True
    for g1 in mats:
        found[close([g1])] = True
        for g2 in mats:
            found[close([g1, g2])] = True
    return list(found.keys())


def min_gens(Q):
    """A minimal generating list for the subgroup Q (tuple of matrices)."""
    Qset = set(Q)
    if Qset == {I2}:
        return []

    def close(gens):
        S = {I2}
        frontier = [I2]
        while frontier:
            nxt = []
            for A in frontier:
                for g in gens:
                    Bm = mmul(g, A)
                    if Bm not in S:
                        S.add(Bm)
                        nxt.append(Bm)
            frontier = nxt
        return S

    for g in Q:
        if close([g]) == Qset:
            return [g]
    for g1, g2 in itertools.combinations([m for m in Q if m != I2], 2):
        if close([g1, g2]) == Qset:
            return [g1, g2]
    raise AssertionError("point subgroup needs > 2 generators")


class Sub:
    """A subgroup H < Gamma of finite index: H = { (M | w_M + L) : M in Q }."""

    __slots__ = ("L", "Q", "w", "key")

    def __init__(self, L, Q, w):
        self.L = L
        self.Q = tuple(sorted(Q))
        self.w = {M: wred(w[M], L) for M in w}
        self.key = (L, tuple(sorted((M, self.w[M]) for M in self.w)))

    def contains(self, el):
        M, v = el
        if M not in self.w:
            return False
        return in_lat(vsub(v, self.w[M]), self.L)


def cocycle_systems(G, Q, B):
    """All systems w: Q -> Q^2, w_M in v_M + Z^2 (mod B), satisfying the
    cocycle condition — i.e. all subgroups H with H ∩ T = B and image Q."""
    gens = min_gens(Q)
    Qset = set(Q)
    if not gens:
        return [{I2: ZERO}]
    box = lat_box(B)
    out = []
    for offsets in itertools.product(box, repeat=len(gens)):
        assign = {I2: ZERO}
        gen_els = [(g, vadd(G.ops[g], o)) for g, o in zip(gens, offsets)]
        ok = True
        frontier = [(I2, ZERO)]
        while frontier and ok:
            nxt = []
            for M1, w1 in frontier:
                for g, wg in gen_els:
                    M, w = gmul((g, wg), (M1, w1))
                    if M not in assign:
                        assign[M] = w
                        nxt.append((M, w))
                    elif not in_lat(vsub(assign[M], w), B):
                        ok = False
                        break
                if not ok:
                    break
            frontier = nxt
        if not ok or set(assign) != Qset:
            continue
        out.append(assign)
    return out


def subgroups_index_k(G, k):
    """All subgroups of index k in the wallpaper group G, deduplicated."""
    P = G.ops
    seen = {}
    for Q in point_subgroups(P.keys()):
        b = len(P) // len(Q)
        if k % b:
            continue
        a = k // b
        for B in sublattices(a):
            cols = lat_cols(B)
            if not all(in_lat(mvec(M, c), B) for M in Q for c in cols):
                continue
            for w in cocycle_systems(G, Q, B):
                s = Sub(B, Q, w)
                seen[s.key] = s
    return list(seen.values())


# ------------------------------------------------------- normaliser & orbits

def gl2_candidates(bound):
    rng = range(-bound, bound + 1)
    out = []
    for a, b, c, d in itertools.product(rng, repeat=4):
        if a * d - b * c in (1, -1):
            out.append(((a, b), (c, d)))
    return out


GL2_BOUND2 = gl2_candidates(2)
GRID_12 = [(F(i, 12), F(j, 12)) for i in range(12) for j in range(12)]


def normaliser_moves(G):
    """Generators of the affine normaliser of Gamma as moves (A, t): one
    compatible t per admissible A, every discrete Theta_I translation for
    A = I, and the integer translations e1, e2.  Continuous directions act
    trivially on subgroup data and are omitted."""
    moves = []
    for A in GL2_BOUND2:
        pairs = conj_pairs(G.ops, A, G.ops)
        if pairs is None:
            continue
        if A == I2:
            # all discrete solutions of (I - M) t ≡ 0 (mod Z^2)
            for t in GRID_12:
                if all(is_int(mvec(IM, t)[0] - rhs[0]) and
                       is_int(mvec(IM, t)[1] - rhs[1])
                       for IM, rhs in pairs):
                    moves.append((A, t))
        else:
            t = solve_cong(pairs)
            if t is not None:
                moves.append((A, t))
    moves.append((I2, (F(1), F(0))))
    moves.append((I2, (F(0), F(1))))
    return moves


def proper_equivalence_moves(G, moves):
    """Moves generating equivalence of colourings under PROPER affine maps.
    A pattern's own improper symmetries (reflections, glides) map the
    colouring to itself with the colours relabelled — conjugation by an
    element of Gamma is a recolouring, not a change of chirality — so inner
    conjugations join the proper normaliser moves.  A colouring is chiral
    iff its class splits when improper OUTER moves are withdrawn."""
    out = [(A, t) for A, t in moves if mdet(A) == 1]
    for M, v in G.ops.items():
        if mdet(M) == -1:
            out.append((M, v))
    return out


def apply_move(sub, move):
    A, t = move
    Ai = minv_uni(A)
    Lcols = lat_cols(sub.L)
    L2 = hnf_of([mvec(A, Lcols[0]), mvec(A, Lcols[1])])
    w2 = {}
    for M, w in sub.w.items():
        Mp = mmul(mmul(A, M), Ai)
        IM = ((1 - Mp[0][0], -Mp[0][1]), (-Mp[1][0], 1 - Mp[1][1]))
        w2[Mp] = vadd(mvec(A, w), mvec(IM, t))
    return Sub(L2, w2.keys(), w2)


def orbits(subs, moves):
    """Partition subgroup instances into orbits under the moves."""
    index = {s.key: s for s in subs}
    unseen = set(index)
    out = []
    while unseen:
        k0 = unseen.pop()
        orbit = {k0}
        frontier = [index[k0]]
        while frontier:
            nxt = []
            for s in frontier:
                for mv in moves:
                    s2 = apply_move(s, mv)
                    assert s2.key in index, "move left the subgroup family"
                    if s2.key not in orbit:
                        orbit.add(s2.key)
                        nxt.append(s2)
            frontier = nxt
        unseen -= orbit
        out.append(frozenset(orbit))
    return out


# ---------------------------------------------------------------- classifier

def mmul_frac(A, B):
    return (
        (F(A[0][0]) * B[0][0] + F(A[0][1]) * B[1][0],
         F(A[0][0]) * B[0][1] + F(A[0][1]) * B[1][1]),
        (F(A[1][0]) * B[0][0] + F(A[1][1]) * B[1][0],
         F(A[1][0]) * B[0][1] + F(A[1][1]) * B[1][1]),
    )


def as_concrete_group(sub):
    """Express H (a subgroup datum) as a wallpaper group in its own primitive
    coordinates: point dict M' -> v' (mod 1) with T = Z^2."""
    Lcols = lat_cols(sub.L)
    Bmat = ((Lcols[0][0], Lcols[1][0]), (Lcols[0][1], Lcols[1][1]))
    d = mdet(Bmat)
    Bi = ((F(Bmat[1][1], d), F(-Bmat[0][1], d)),
          (F(-Bmat[1][0], d), F(Bmat[0][0], d)))
    ops = {}
    for M, w in sub.w.items():
        Mp = mmul_frac(Bi, mmul_frac(M, Bmat))
        for row in Mp:
            for x in row:
                assert is_int(x), ("H point matrix not integral in L-basis", M)
        Mp = ((int(Mp[0][0]), int(Mp[0][1])), (int(Mp[1][0]), int(Mp[1][1])))
        ops[Mp] = vmod1(mvec(Bi, w))
    return ops


GL2_BOUND3 = gl2_candidates(3)
_classify_cache = {}


def classify_with_map(ops):
    """Which of the 17 standard groups is (T=Z^2, ops) affinely equivalent
    to?  Returns (hm, A, t) with (A|t) ops (A|t)^{-1} = standard model;
    asserts uniqueness of the type."""
    finger = tuple(sorted((mdet(M), M[0][0] + M[1][1]) for M in ops))
    hits = []
    for g in GROUPS.values():
        if g.finger != finger:
            continue
        for A in GL2_BOUND3:
            pairs = conj_pairs(ops, A, g.ops)
            if pairs is None:
                continue
            t = solve_cong(pairs)
            if t is not None:
                hits.append((g.hm, A, t))
                break
    assert len(hits) == 1, ("classification not unique/found",
                            [h[0] for h in hits], ops)
    return hits[0]


def classify_concrete(ops):
    key = tuple(sorted(ops.items()))
    if key in _classify_cache:
        return _classify_cache[key]
    hm = classify_with_map(ops)[0]
    _classify_cache[key] = hm
    return hm


# ------------------------------------------------------------- coset actions

def coset_reps(G, sub, k):
    """BFS coset representatives of Gamma/H (exact elements)."""
    reps = [(I2, ZERO)]
    frontier = [(I2, ZERO)]
    gens = G.full_gens + [ginv(g) for g in G.full_gens]
    while frontier:
        nxt = []
        for r in frontier:
            for g in gens:
                e = gmul(g, r)
                if not any(sub.contains(gmul(ginv(rr), e)) for rr in reps):
                    reps.append(e)
                    nxt.append(e)
        frontier = nxt
    assert len(reps) == k, ("coset count", len(reps), k)
    return reps


def coset_index(sub, reps, el):
    for j, r in enumerate(reps):
        if sub.contains(gmul(ginv(r), el)):
            return j
    raise AssertionError("element in no coset")


def perm_of(G, sub, reps, el):
    return tuple(coset_index(sub, reps, gmul(el, r)) for r in reps)


def perm_mul(p, q):
    return tuple(p[q[i]] for i in range(len(p)))


def perm_group(perms, k):
    idp = tuple(range(k))
    S = {idp}
    frontier = [idp]
    while frontier:
        nxt = []
        for p in frontier:
            for q in perms:
                r = perm_mul(q, p)
                if r not in S:
                    S.add(r)
                    nxt.append(r)
        frontier = nxt
    return S


def perm_order(p):
    n = 1
    q = p
    idp = tuple(range(len(p)))
    while q != idp:
        q = perm_mul(p, q)
        n += 1
    return n


def action_label(S, k):
    """Name the transitive permutation group S <= S_k (k <= 6)."""
    n = len(S)
    maxo = max(perm_order(p) for p in S)
    cyclic = (maxo == n)
    abelian = all(perm_mul(p, q) == perm_mul(q, p) for p in S for q in S)
    if cyclic:
        return "C%d" % n
    if abelian and n == 4:
        return "C2×C2"
    if n == 6:
        return "S3"
    if n == 8:
        return "D4"
    if n == 10:
        return "D5"
    if n == 12:
        return "D6" if maxo == 6 else "A4"
    if n == 18:
        return "3²:2"
    if n == 20:
        return "F20"
    if n == 24:
        return "S4"
    if n == 36:
        return "S3×S3" if maxo == 6 else "3²:4"
    if n == 48:
        return "C2×S4"
    if n == 60:
        return "A5"
    if n == 72:
        return "S3≀C2"
    if n == 120:
        return "S5"
    if n == 720:
        return "S6"
    return "T%d" % n


# ------------------------------------------------------------------- kernels

def kernel_sub(G, sub, reps, k):
    """The colour-fixing subgroup K (kernel of the coset action) as a Sub."""
    idp = tuple(range(k))
    e1p = perm_of(G, sub, reps, (I2, (F(1), F(0))))
    e2p = perm_of(G, sub, reps, (I2, (F(0), F(1))))
    o1, o2 = perm_order(e1p), perm_order(e2p)
    vecs = [(o1, 0), (0, o2)]
    p1cur = idp
    for m1 in range(o1):
        p2cur = p1cur
        for m2 in range(o2):
            if (m1, m2) != (0, 0) and p2cur == idp:
                vecs.append((m1, m2))
            p2cur = perm_mul(e2p, p2cur)
        p1cur = perm_mul(e1p, p1cur)
    L0 = hnf_of(vecs)
    box0 = lat_box(L0)
    wk = {I2: ZERO}
    for M, v in G.ops.items():
        if M == I2:
            continue
        for o in box0:
            el = (M, vadd(v, o))
            if perm_of(G, sub, reps, el) == idp:
                wk[M] = el[1]
                break
    return Sub(L0, wk.keys(), wk)


# ---------------------------------------------------------------- rendering

def render_spec(G, sub, reps, k, kern):
    """Render data: one op per (point matrix, offset mod L0) with its colour;
    the renderer tiles the plane by the colour-period cell L0."""
    L0 = kern.L
    box0 = lat_box(L0)
    ops = []
    for M, v in G.ops.items():
        for o in box0:
            el = (M, vadd(v, o))
            ops.append({
                "M": [list(M[0]), list(M[1])],
                "v": [float(el[1][0]), float(el[1][1])],
                "color": coset_index(sub, reps, el),
            })
    # base point: maximise the minimum distance between orbit points of the
    # UNCOLOURED pattern (point images + integer translates) — floats only
    B = G.basis
    mats = [((float(M[0][0]), float(M[0][1])), (float(M[1][0]), float(M[1][1])),
             float(v[0]), float(v[1])) for M, v in G.ops.items()]
    shifts = [(i, j) for i in (-1, 0, 1) for j in (-1, 0, 1)]

    def cart(x, y):
        return (B[0][0] * x + B[1][0] * y, B[0][1] * x + B[1][1] * y)

    best = None
    for bx in range(0, 12):
        for by in range(0, 12):
            base = (bx / 12 + 0.031, by / 12 + 0.017)
            pts = []
            for (r0, r1, vx, vy) in mats:
                x = r0[0] * base[0] + r0[1] * base[1] + vx
                y = r1[0] * base[0] + r1[1] * base[1] + vy
                pts.append((x, y))
            dmin = None
            for i in range(len(pts)):
                for j in range(len(pts)):
                    for s1, s2 in shifts:
                        if i == j and s1 == 0 and s2 == 0:
                            continue
                        a = cart(pts[i][0] - pts[j][0] - s1, pts[i][1] - pts[j][1] - s2)
                        d = a[0] * a[0] + a[1] * a[1]
                        if dmin is None or d < dmin:
                            dmin = d
            if best is None or dmin > best[0]:
                best = (dmin, base)
    base = best[1]
    return {
        "basis": [[B[0][0], B[0][1]], [B[1][0], B[1][1]]],
        "cell": [list(lat_cols(L0)[0]), list(lat_cols(L0)[1])],
        "k": k,
        "ops": ops,
        "base": [base[0], base[1]],
        "minDist": math.sqrt(best[0]),
    }


# --------------------------------------------- the clockwork correspondence

def _fr(x):
    """Exact rational from a catalog float (everything sits on a 1/12 grid)."""
    f = F(x).limit_denominator(12)
    assert abs(float(f) - x) < 1e-9, x
    return f


def clockwork_pairs(catalog):
    """For every forward (clockwork) group in the site catalog, reconstruct
    the coloured pair in the spatial projection's own primitive coordinates:
    Gamma = the projection, H = the kernel of the clock phase, plus the
    clock order k.

    Catalog render ops are coset representatives modulo Z^2 x Z (integer
    spatial translations carry tau = 0), so the projection's translation
    lattice T_proj is Z^2 enlarged by any centring vectors (ops with M = I,
    v not in Z^2), and the clock phase is a homomorphism Gamma -> Z/k that
    is linear on T_proj."""
    out = []
    for g in catalog["groups"]:
        if not g["forward"]:
            continue
        ops = []
        for op in g["render"]["ops"]:
            assert op["s"] == 1, (g["id"], "forward group with reversal")
            M = ((op["M"][0][0], op["M"][0][1]), (op["M"][1][0], op["M"][1][1]))
            v = (_fr(op["v"][0]), _fr(op["v"][1]))
            tau = _fr(op["tau"]) % 1
            ops.append((M, v, tau))
        k = 1
        for _, _, tau in ops:
            k = k * tau.denominator // math.gcd(k, tau.denominator)
        if k == 1:
            out.append({"id": g["id"], "k": 1, "base": g["base"]})
            continue
        # T_proj = Z^2 + centring vectors, with the phase of each generator
        cents = [(v, tau) for M, v, tau in ops if M == I2]
        den = 1
        for v, _ in cents:
            for x in v:
                den = den * x.denominator // math.gcd(den, x.denominator)
        sup = hnf_of([(int(v[0] * den), int(v[1] * den)) for v, _ in cents]
                     + [(den, 0), (0, den)])
        b1 = (F(sup[0][0], den), F(0))
        b2 = (F(sup[0][1], den), F(sup[1][1], den))
        Bmat = ((b1[0], b2[0]), (b1[1], b2[1]))
        d = Bmat[0][0] * Bmat[1][1] - Bmat[0][1] * Bmat[1][0]
        Bi = ((Bmat[1][1] / d, -Bmat[0][1] / d),
              (-Bmat[1][0] / d, Bmat[0][0] / d))

        def phase_of_translation(b):
            """Clock phase of the T_proj vector b (original coordinates):
            0 on Z^2; on a centring coset, the centring's tau."""
            if is_int(b[0]) and is_int(b[1]):
                return F(0)
            for v, tau in cents:
                dd = vsub(b, v)
                if is_int(dd[0]) and is_int(dd[1]):
                    return tau
            raise AssertionError("translation not in T_proj")

        tau1 = phase_of_translation(b1)
        tau2 = phase_of_translation(b2)
        proj = {}
        taum = {}
        for M, v, tau in ops:
            Mp = mmul_frac(Bi, mmul_frac(M, Bmat))
            for row in Mp:
                for x in row:
                    assert is_int(x), (g["id"], "point matrix not integral")
            Mp = ((int(Mp[0][0]), int(Mp[0][1])), (int(Mp[1][0]), int(Mp[1][1])))
            vp = mvec(Bi, v)
            if Mp in proj:
                dd = vsub(proj[Mp], vp)
                assert is_int(dd[0]) and is_int(dd[1]), (g["id"], "coset clash")
                continue
            proj[Mp] = vmod1(vp)
            # rebase the op's tau to the canonical representative vmod1(vp):
            # subtracting the integer part n (in T_proj coords) shifts tau
            # by -phase(n) = -(n1 tau1 + n2 tau2)
            n = vsub(vp, vmod1(vp))
            taum[Mp] = (tau - n[0] * tau1 - n[1] * tau2) % 1
        out.append({"id": g["id"], "k": k, "base": g["base"],
                    "proj": proj, "taum": taum, "tau12": (tau1, tau2)})
    return out


def match_clockwork(results, catalog):
    """Assign to each nontrivial clockwork group its coloured-crystal class.
    Returns {gid: coloredId} and fills r['clockwork']."""
    by_key = {}
    for r in results:
        for kk in r["orbit"]:
            by_key[(r["hm"], r["k"], kk)] = r
    for r in results:
        r["clockwork"] = []
    pairs = clockwork_pairs(catalog)
    trivial = [p for p in pairs if p["k"] == 1]
    assert len(trivial) == 17, len(trivial)
    out = {}
    for p in pairs:
        if p["k"] == 1:
            continue
        k = p["k"]
        tau1, tau2 = p["tau12"]
        # kernel H = ker(phase): translation lattice first
        vecs = [(k, 0), (0, k)]
        for m1 in range(k):
            for m2 in range(k):
                if (m1, m2) != (0, 0) and (m1 * tau1 + m2 * tau2) % 1 == 0:
                    vecs.append((m1, m2))
        Lproj = hnf_of(vecs)
        # point part: for each coset (M | vp) find n with
        # tau(M) + n1 tau1 + n2 tau2 ≡ 0 (mod 1)
        wk = {}
        for M, vp in p["proj"].items():
            for n1 in range(k):
                for n2 in range(k):
                    if (p["taum"][M] + n1 * tau1 + n2 * tau2) % 1 == 0:
                        wk[M] = vadd(vp, (F(n1), F(n2)))
                        break
                else:
                    continue
                break
        # move the pair onto the standard model of its type
        hm, A, t = classify_with_map(p["proj"])
        assert hm == p["base"], (p["id"], hm, p["base"])
        Ai = minv_uni(A)
        w2 = {}
        for M, w in wk.items():
            Mp = mmul(mmul(A, M), Ai)
            IM = ((1 - Mp[0][0], -Mp[0][1]), (-Mp[1][0], 1 - Mp[1][1]))
            w2[Mp] = vadd(mvec(A, w), mvec(IM, t))
        Lcols = lat_cols(Lproj)
        Lstd = hnf_of([mvec(A, Lcols[0]), mvec(A, Lcols[1])])
        sub = Sub(Lstd, w2.keys(), w2)
        key = (hm, k, sub.key)
        assert key in by_key, (p["id"], "pair not found among enumerated")
        r = by_key[key]
        assert r["cyclic"] and r["k"] == k, (p["id"], r["id"])
        r["clockwork"].append(p["id"])
        out[p["id"]] = r["id"]
    ncls = len(set(out.values()))
    print("clockwork matching: 17 trivial (k=1), %d nontrivial -> %d "
          "coloured classes" % (len(out), ncls))
    return out


# --------------------------------------------------------------------- main

def enumerate_all(kmax=6, verbose=True):
    """Enumerate all colour-group classes for 2 <= k <= kmax."""
    results = []
    for hm in ORDER17:
        G = GROUPS[hm]
        moves = normaliser_moves(G)
        proper_moves = proper_equivalence_moves(G, moves)
        for k in range(2, kmax + 1):
            subs = subgroups_index_k(G, k)
            index = {s.key: s for s in subs}
            full = orbits(subs, moves)
            proper = orbits(subs, proper_moves)
            for orb in full:
                sub = index[sorted(orb)[0]]
                nprop = sum(1 for po in proper if po & orb)
                results.append({"hm": hm, "k": k, "sub": sub, "orbit": orb,
                                "properClasses": nprop})
            if verbose:
                exp = TABLE_8_2_1[hm][k - 2]
                mark = "OK" if len(full) == exp else "EXPECTED %d" % exp
                print("  %-5s k=%d  subgroups=%3d  classes=%2d  %s"
                      % (hm, k, len(subs), len(full), mark))
    return results


def main():
    print("Wallpaper models:", ", ".join(
        "%s(%d)" % (hm, len(GROUPS[hm].ops)) for hm in ORDER17))

    for hm in ORDER17:
        got = classify_concrete(GROUPS[hm].ops)
        assert got == hm, (hm, got)
    print("classifier self-test: 17/17 OK")

    results = enumerate_all()

    for hm in ORDER17:
        for k in range(2, 7):
            n = sum(1 for r in results if r["hm"] == hm and r["k"] == k)
            assert n == TABLE_8_2_1[hm][k - 2], (hm, k, n)
    for k in range(2, 7):
        n = sum(1 for r in results if r["k"] == k)
        assert n == TABLE_TOTALS[k - 2], (k, n)
    print("Table 8.2.1 reproduced: 46 + 23 + 96 + 14 + 90 = 269  ✓")

    # --- enrich: types, actions, kernels
    for r in results:
        G = GROUPS[r["hm"]]
        sub = r["sub"]
        k = r["k"]
        r["subType"] = classify_concrete(as_concrete_group(sub))
        reps = coset_reps(G, sub, k)
        r["reps"] = reps
        gen_perms = [perm_of(G, sub, reps, g) for g in G.full_gens]
        S = perm_group(gen_perms, k)
        r["action"] = action_label(S, k)
        r["normal"] = (len(S) == k)
        r["cyclic"] = r["normal"] and r["action"] == "C%d" % k
        kern = kernel_sub(G, sub, reps, k)
        r["kern"] = kern
        r["kernType"] = classify_concrete(as_concrete_group(kern))

    def sort_key(r):
        return (r["k"], ORDER17.index(r["hm"]), ORDER17.index(r["subType"]),
                lat_index(r["sub"].L), str(r["sub"].key))

    results.sort(key=sort_key)
    counters = {}
    for r in results:
        c = counters.setdefault((r["k"], r["hm"]), [0])
        c[0] += 1
        r["id"] = "c%d-%s-%d" % (r["k"], r["hm"], c[0])

    chiral = [r for r in results if r["properClasses"] > 1]
    print("chiral classes under proper-affine equivalence: %d" % len(chiral))
    for r in chiral:
        print("   ", r["id"], "%s / %s" % (r["hm"], r["subType"]),
              "k=%d" % r["k"], "-> %d proper classes" % r["properClasses"])

    print("\nH-type census (k=2):")
    for hm in ORDER17:
        rows = [r for r in results if r["hm"] == hm and r["k"] == 2]
        if rows:
            print("  %-5s: %s" % (hm, ", ".join(r["subType"] for r in rows)))

    print("\naction census:")
    for k in range(2, 7):
        labels = {}
        for r in results:
            if r["k"] == k:
                labels[r["action"]] = labels.get(r["action"], 0) + 1
        print("  k=%d: %s" % (k, ", ".join(
            "%s×%d" % (a, n) for a, n in sorted(labels.items()))))
    ncyc = sum(1 for r in results if r["cyclic"])
    print("cyclic (clock-drivable) colourings, k=2..6: %d" % ncyc)

    # --- the clockwork correspondence, from the site catalog
    with open(os.path.join(DOCS, "data", "catalog.json"), encoding="utf-8") as f:
        catalog = json.load(f)
    match_clockwork(results, catalog)
    nboost = 0
    for r in results:
        r["boostable"] = (r["cyclic"] and not r["clockwork"]
                          and r["k"] in (2, 3, 4, 6))
        nboost += r["boostable"]
    print("cyclic colourings with no clockwork realisation (boostable): %d;"
          " plus %d five-colour cyclics (no crystallographic 5-clock)"
          % (nboost, sum(1 for r in results if r["cyclic"] and r["k"] == 5)))

    for r in results:
        r["render"] = render_spec(GROUPS[r["hm"]], r["sub"], r["reps"],
                                  r["k"], r["kern"])

    orb_of = {hm: GROUPS[hm].orb for hm in ORDER17}
    out_groups = []
    for r in results:
        a = lat_index(r["sub"].L)
        out_groups.append({
            "id": r["id"],
            "k": r["k"],
            "base": {"hm": r["hm"], "orb": orb_of[r["hm"]]},
            "sub": {"hm": r["subType"], "orb": orb_of[r["subType"]]},
            "kernel": {"hm": r["kernType"], "orb": orb_of[r["kernType"]]},
            "action": r["action"],
            "normal": r["normal"],
            "cyclic": r["cyclic"],
            "chiral": r["properClasses"] > 1,
            "properClasses": r["properClasses"],
            "latticeIndex": a,
            "pointIndex": r["k"] // a,
            "clockwork": sorted(r["clockwork"],
                                key=lambda s: int(s.lstrip("g"))),
            "boostable": r["boostable"],
            "render": r["render"],
        })

    meta = {
        "totals": {str(k): TABLE_TOTALS[k - 2] for k in range(2, 7)},
        "total": len(out_groups),
        "perGroup": {hm: {str(k): TABLE_8_2_1[hm][k - 2] for k in range(2, 7)}
                     for hm in ORDER17},
        "chiral": len(chiral),
        "cyclic": ncyc,
        "note": "pairs (Gamma, H) of index k <= 6 up to affine equivalence "
                "of pairs; anchors: Grünbaum-Shephard Table 8.2.1 = "
                "Jarratt-Schwarzenberger Table 5 = Wieting. properClasses "
                "counts orientation-preserving (proper-affine) classes.",
    }
    path = os.path.join(DOCS, "data", "colored.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump({"meta": meta, "groups": out_groups}, f, indent=1,
                  ensure_ascii=False)
    print("\nwrote %s  (%d groups)" % (path, len(out_groups)))


if __name__ == "__main__":
    main()
