"""k-colour pattern types of the plane, k <= 6: exact enumeration.

Generalises enumerate_patterns.py (the two-colour case, Grünbaum & Shephard's
88) to every perfect k-colouring with k <= 6.  A k-coloured pattern type is a
chain  S <= H <= Gamma  — S the full site symmetry of the motif's seat, H the
stabiliser of one colour (index k; the colour group is the pair Gamma > H of
catalogue D) — up to simultaneous conjugation by the affine normaliser
N(Gamma).  The admissibility condition is S ⊆ H: every symmetry fixing the
marked copy fixes its colour.

For k = 2 the subgroup H is normal, so the chain is determined by the
Gamma-orbit of the seat (the *stratum*) together with H, which is how
enumerate_patterns.py computes the 88.  For k >= 3 the subgroup need not be
normal and S ⊆ H depends on which point of the stratum carries the marked
copy: the correct datum is a *based* chain (seat point, H).  This module
therefore enumerates, per colour-group class with representative H:

  * the admissible based seats — all Gamma-images of each symbolic stratum's
    base point (reduced modulo T_H, the lattice of translations normalising
    H) whose full stabiliser lies in H; for segment-free mirror edges the
    based datum is the conjugated reflection itself;
  * orbits of these under Stab_{N(Gamma)}(H), generated by Schreier
    generators obtained from a transversal of the subgroup-key orbit.

Each orbit is one pattern type.  For display, a representative is re-based so
the seat is a *literal* symbol of the annotated signature (a letter's own
mirror or centre), conjugating H accordingly within its class — so the red
seat mark always sits on colour-preserving symbols.

Anchors:
  k=1  ->  52 marked strata = the 51 uncoloured pattern types PP1..PP51
           (PP48 splits into varieties A and B);
  k=2  ->  88 types, anchors regression-checked against
           docs/data/two-color-patterns.json;
  k=3  ->  compared against the 59 three-colour types of G&S Figures
           8.2.3/8.3.6 via the sibling repo's color-pattern-catalog.json;
  k>=4 ->  no published pattern-type tables exist; labels are systematic
           extensions PPn[k] with the colour-group ordinal of catalogue D.

Colour bookkeeping: colours are the left cosets of the pane's subgroup H,
labelled A.. in the BFS order of coset_reps; the colour permutation of g is
sigma_g(i) = index of g·r_i, so translations act on a rendered copy's colour
by sigma_{e1}^i · sigma_{e2}^j — the renderer needs only the base colour of
each of the |P| coset ops and the two translation permutations.

Emits docs/data/patterns.json.  Run:  python3 enumerate_patterns_k.py
"""

from fractions import Fraction
import json
import math
import os
import pickle
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import enumerate_colored as EC  # noqa: E402
import enumerate_patterns as EP  # noqa: E402
from enumerate_colored import (  # noqa: E402
    F, I2, ZERO, GROUPS, ORDER17, mdet, subgroups_index_k, normaliser_moves,
    apply_move, classify_concrete, as_concrete_group, lat_index, coset_reps,
    perm_of, perm_group, action_label, kernel_sub, TABLE_8_2_1, Sub,
    lat_box, lat_cols, hnf_of, wred, gmul, ginv,
)
from enumerate_patterns import (  # noqa: E402
    CHAIM, build_chaim, check_relations, in_group, strata_of, stabiliser,
    sub_contains_set, minv_uni, mmul, mvec, vadd, vsub, PP_TABLE, cart,
    cart_matrix, view_basis, seat_point, min_orbit_distance, line_of,
    signature_string, stab_type,
)

HERE = os.path.dirname(os.path.abspath(__file__))
DOCS = os.path.join(HERE, "..", "docs")
KMAX = 6
LETTERS = "ABCDEF"
SUBSCRIPT = {"1": "₁", "2": "₂", "3": "₃", "4": "₄", "5": "₅", "6": "₆",
             "7": "₇", "8": "₈", "9": "₉", "0": "₀"}


def subscript(s):
    return "".join(SUBSCRIPT[ch] for ch in str(s))


def cycle_string(perm):
    """'(AB)(CD)' / '(ABC)' / '1' from an image tuple."""
    n = len(perm)
    seen = [False] * n
    out = []
    for i in range(n):
        if seen[i] or perm[i] == i:
            seen[i] = True
            continue
        cyc = [i]
        seen[i] = True
        j = perm[i]
        while j != i:
            cyc.append(j)
            seen[j] = True
            j = perm[j]
        out.append("(" + "".join(LETTERS[c] for c in cyc) + ")")
    return "".join(out) if out else "1"


# ---------------------------------------------------------- affine map words

def mv_compose(a, b):
    """(A1|t1) ∘ (A2|t2) = (A1 A2 | A1 t2 + t1)."""
    (A1, t1), (A2, t2) = a, b
    return (mmul(A1, A2), vadd(mvec(A1, t2), t1))


def mv_inv(a):
    A, t = a
    Ai = minv_uni(A)
    w = mvec(Ai, t)
    return (Ai, (-w[0], -w[1]))


IDMOVE = (I2, ZERO)


# ------------------------------------------------------------ colour groups

def full_group_sub(G):
    """H = Gamma itself as a Sub (the trivial 1-colouring)."""
    w = {M: v for M, v in G.ops.items()}
    return Sub(((1, 0), (0, 1)), w.keys(), w)


def all_colour_groups():
    """Colour-group classes for k = 1..KMAX with catalogue-D ids (the sort of
    enumerate_colored.main, so c{k}-{hm}-{n} match colored.json)."""
    results = EC.enumerate_all(kmax=KMAX, verbose=False)
    for r in results:
        r["subType"] = classify_concrete(as_concrete_group(r["sub"]))
    results.sort(key=lambda r: (r["k"], ORDER17.index(r["hm"]),
                                ORDER17.index(r["subType"]),
                                lat_index(r["sub"].L), str(r["sub"].key)))
    counters = {}
    for r in results:
        c = counters.setdefault((r["k"], r["hm"]), [0])
        c[0] += 1
        r["id"] = "c%d-%s-%d" % (r["k"], r["hm"], c[0])
    for hm in ORDER17:
        for k in range(2, KMAX + 1):
            n = sum(1 for r in results if r["hm"] == hm and r["k"] == k)
            assert n == TABLE_8_2_1[hm][k - 2], (hm, k, n)
    trivial = []
    for hm in ORDER17:
        G = GROUPS[hm]
        sub = full_group_sub(G)
        trivial.append({"hm": hm, "k": 1, "sub": sub,
                        "orbit": frozenset({sub.key}),
                        "properClasses": 1, "subType": hm,
                        "id": "c1-%s-1" % hm})
    return trivial + results


# ------------------------------------------------------- based-seat machinery

def translation_stabilizer(H):
    """HNF of T_H = { n in Z^2 : (I|n) H (I|n)^{-1} = H }; contains H ∩ T."""
    gens = [tuple(int(x) for x in v) for v in lat_cols(H.L)]
    for n in lat_box(H.L):
        if n == (F(0), F(0)):
            continue
        if apply_move(H, (I2, n)).key == H.key:
            gens.append((int(n[0]), int(n[1])))
    TH = hnf_of(gens)
    assert apply_move(H, (I2, (F(TH[0][0]), F(0)))).key == H.key
    return TH


def conj_el(g, el):
    return gmul(gmul(g, el), ginv(g))


def edge_line_key(el, TH):
    """Canonical key of a reflection's mirror line modulo conjugation by
    translations in T_H (cf. enumerate_patterns.canon_line, which reduces
    modulo all of Gamma and Z^2)."""
    M, w = el
    IM = ((1 - M[0][0], -M[0][1]), (-M[1][0], 1 - M[1][1]))
    g1 = (IM[0][0], IM[1][0])
    g2 = (IM[0][1], IM[1][1])
    u0 = g1 if g1 != (0, 0) else g2
    gg = math.gcd(abs(u0[0]), abs(u0[1]))
    u0 = (u0[0] // gg, u0[1] // gg)
    # w is parallel to u0 for a reflection
    lam = (F(w[0]) / u0[0]) if u0[0] else (F(w[1]) / u0[1])
    assert vsub(w, (lam * u0[0], lam * u0[1])) == ZERO, ("not a reflection", el)
    # (I - M) T_H = step * u0 * Z
    t1, t2 = lat_cols(TH)
    steps = []
    for t in (t1, t2):
        im = mvec(IM, t)
        if im == (0, 0):
            continue
        c = (F(im[0]) / u0[0]) if u0[0] else (F(im[1]) / u0[1])
        assert c.denominator == 1
        steps.append(abs(int(c)))
    step = 0
    for s in steps:
        step = math.gcd(step, s)
    assert step > 0, ("degenerate edge lattice", el, TH)
    return ("ln", M, lam % step)


def based_objects(G, H, TH, strata_list):
    """All admissible based seats for the subgroup H, as
    key -> {"strata": set of stratum indices, "datum": exact datum,
            "witness": (stratum index, g) with datum = image of the
            stratum's own base under g}."""
    box = lat_box(TH)
    out = {}

    def add(key, i, datum, g):
        rec = out.setdefault(key, {"strata": set(), "datum": datum,
                                   "witnesses": {}})
        rec["strata"].add(i)
        rec["witnesses"].setdefault(i, g)

    for i, s in enumerate(strata_list):
        if s["kind"] == "interior":
            add(("int",), i, None, IDMOVE)
            continue
        if s["point"] is not None:
            p = s["point"]
            for M, v in G.ops.items():
                for n in box:
                    g = (M, vadd(v, n))
                    q = vadd(mvec(M, p), g[1])
                    qr = wred(q, TH)
                    S = stabiliser(G, qr)
                    if not sub_contains_set(H, S):
                        continue
                    # witness with the exact reduction translation folded in
                    shift = vsub(qr, q)
                    gw = mv_compose((I2, shift), g)
                    add(("pt", qr), i, qr, gw)
        else:
            el = [e for e in s["S"] if e[0] != I2][0]
            for M, v in G.ops.items():
                for n in box:
                    g = (M, vadd(v, n))
                    el2 = conj_el(g, el)
                    if not H.contains(el2):
                        continue
                    add(edge_line_key(el2, TH), i, el2, g)
    return out


def stabilizer_generators(H, orbit_keys, index, moves):
    """Schreier generators of Stab_{N(Gamma)}(H) from the move action on the
    subgroup-key orbit, as affine maps (A | t).  Schreier's lemma needs the
    generating set closed under inverses."""
    moves = list({mv: True for mv in
                  list(moves) + [mv_inv(mv) for mv in moves]})
    trans = {H.key: IDMOVE}
    frontier = [H.key]
    while frontier:
        nxt = []
        for x in frontier:
            for mv in moves:
                y = apply_move(index[x], mv).key
                if y not in trans:
                    trans[y] = mv_compose(mv, trans[x])
                    nxt.append(y)
        frontier = nxt
    assert set(trans) == set(orbit_keys), "transversal misses orbit keys"
    sgens = {}
    for x, ux in trans.items():
        for mv in moves:
            y = apply_move(index[x], mv).key
            s = mv_compose(mv_inv(trans[y]), mv_compose(mv, ux))
            if s != IDMOVE:
                sgens[s] = True
    for s in sgens:
        assert apply_move(H, s).key == H.key, ("Schreier gen moves H", s)
    return list(sgens)


def based_orbits(G, H, TH, strata_list, sgens, objs):
    """Partition the admissible based seats into Stab(H)-orbits."""

    def act(key, mv):
        A, t = mv
        if key[0] == "int":
            return ("int",)
        if key[0] == "pt":
            q = vadd(mvec(A, key[1]), t)
            return ("pt", wred(q, TH))
        el = objs[key]["datum"]
        M, v = el
        Ai = minv_uni(A)
        Mp = mmul(mmul(A, M), Ai)
        wp = vsub(vadd(t, mvec(A, v)), mvec(Mp, t))
        return edge_line_key((Mp, wp), TH)

    # iterate in dict insertion order: deterministic across processes
    # (set.pop() order is hash-randomised and leaked into label suffixes)
    seen = set()
    orbits_ = []
    for k0 in objs:
        if k0 in seen:
            continue
        orb = {k0}
        frontier = [k0]
        while frontier:
            nxt = []
            for kk in frontier:
                for mv in sgens:
                    k2 = act(kk, mv)
                    assert k2 in objs, (G.hm, "based seat moved outside")
                    if k2 not in orb:
                        orb.add(k2)
                        nxt.append(k2)
            frontier = nxt
        seen |= orb
        orbits_.append(orb)
    return orbits_


# ------------------------------------------------------------------ labels

def base_pp(hm, stype, letters):
    """Underlying uncoloured pattern number and variety letter."""
    n = PP_TABLE[hm][stype]
    suffix = ""
    if hm == "p4m" and stype == "d1":
        n = 39 if "Q" in letters else 38
    if hm == "p6m" and stype == "d1":
        if "P" in letters:
            n = 47
        elif "Q" in letters:
            n, suffix = 48, "A"
        else:
            n, suffix = 48, "B"
    return n, suffix


def star_rule(hm, rep, cycles):
    """The G&S star for pmm PP15-style splits: '' when the seat mirror is
    adjacent (perpendicular) to a colour-moving mirror, '*' when parallel."""
    if rep["kind"] != "edge":
        return None
    moving = {name for name, p in cycles.items()
              if p != tuple(range(len(p)))}
    order = [name for name, _ in CHAIM[hm]["gens"]]
    L = rep["letters"][0]
    if L not in order:
        return None
    i = order.index(L)
    nleft = order[(i - 1) % len(order)]
    nright = order[(i + 1) % len(order)]
    adjacent = (nleft in moving) or (nright in moving)
    return "" if adjacent else "*"


ORDER_KIND = {"interior": 0, "edge": 1, "corner": 2, "gyration": 3}


def line_word(hm, rep, Ht, reps_c, k, n_copies=12):
    """Colour word of the copies along an edge seat's mirror line, starting
    at the seat and walking in the +direction; classifies the variant.
    Returns (word, cls) with cls in {'const', 'single', 'doubled'}."""
    if rep["kind"] != "edge" or rep.get("line") is None:
        return None, None
    G = GROUPS[hm]
    p0, dvec = rep["line"]
    seed = rep["point"]
    if seed is None:
        # segment-free edge: the seat is anywhere on the line
        seed = p0
    hits = {}
    for M, v in G.ops.items():
        for nx in range(-8, 9):
            for ny in range(-8, 9):
                g = (M, vadd(v, (F(nx), F(ny))))
                q = vadd(mvec(M, rep["point"] if rep["point"] is not None
                              else p0), g[1])
                w = vsub(q, seed)
                if w[0] * dvec[1] - w[1] * dvec[0] != 0:
                    continue
                s = (w[0] / dvec[0]) if dvec[0] else (w[1] / dvec[1])
                if s < 0 or s in hits:
                    continue
                hits[s] = EC.coset_index(Ht, reps_c, g)
    word = "".join(LETTERS[hits[s]] for s in sorted(hits)[:n_copies])
    if len(set(word)) == 1:
        cls = "const"
    elif any(word[i] == word[i + 1] for i in range(len(word) - 1)):
        cls = "doubled"
    else:
        cls = "single"
    return word, cls


# Star order for the k=3 buckets that outgrow the book's figures, matched to
# the printed panels of Figs 8.2.3/8.3.6 by the seat-line colour word (the
# panels' variants were identified visually; see the session notes).  Types
# beyond the list order (or beyond the book's count) get extra stars.
K3_STAR_ORDER = {
    ("c3-pmm-1", 15): [("P", "single"), ("Q", "const"), ("P", "doubled")],
    ("c3-cmm-1", 19): [("P", "const"), ("Q", "single"), ("Q", "doubled")],
    ("c3-p3m1-2", 28): [("P", "const"), ("Q", "const")],
    ("c3-p6m-2", 47): [("P", "single"), ("P", "doubled"), ("P", "doubled")],
}


def assign_labels(records, gsmap):
    """Attach pretty label + anchor id per type record (in place)."""
    by_group = {}
    for t in records:
        by_group.setdefault(t["colour_group"], []).append(t)
    notes = []
    for cid, recs in by_group.items():
        hm, k = recs[0]["hm"], recs[0]["k"]
        recs.sort(key=lambda t: (ORDER_KIND[t["rep"]["kind"]], t["pp"],
                                 t["variety"], t["rep"]["letters"]))
        ordinal = int(cid.split("-")[-1])
        gs_sym = gsmap.get(cid, {}).get("gs")
        gsub = ""
        if gs_sym and not gs_sym.endswith("]"):
            gsub = gs_sym[gs_sym.index("]") + 1:]
        buckets = {}
        for t in recs:
            buckets.setdefault((t["pp"], t["variety"]), []).append(t)
        for (pp, variety), ts in buckets.items():
            if len(ts) == 1:
                ts[0]["star"], ts[0]["suffix"] = 0, ""
            elif k == 3 and (cid, pp) in K3_STAR_ORDER:
                order_spec = K3_STAR_ORDER[(cid, pp)]
                keyed = []
                for t in ts:
                    word, cls = line_word(hm, t["rep"], t["H"], t["reps"], k)
                    keyed.append((t, (t["rep"]["letters"][0], cls), word))
                assert sorted(x[1] for x in keyed) == sorted(order_spec), (
                    cid, pp, [x[1] for x in keyed], order_spec)
                # order by the spec, ties broken by the colour word
                pos = {}
                ordered = []
                for spec in order_spec:
                    cands = sorted((x for x in keyed
                                    if x[1] == spec and id(x[0]) not in pos),
                                   key=lambda x: x[2])
                    x = cands[0]
                    pos[id(x[0])] = True
                    ordered.append(x[0])
                for i, t in enumerate(ordered):
                    t["star"], t["suffix"] = i, ""
                ts[:] = ordered
                notes.append("%s PP%d%s[3]: %d variants ordered to the "
                             "printed panels (seat-line words %s)"
                             % (cid, pp, variety, len(ts),
                                [x[2][:6] for x in keyed]))
            elif len(ts) == 2 and k <= 3:
                stars = [star_rule(hm, t["rep"], t["cycles"]) for t in ts]
                if sorted(x for x in stars if x is not None) == ["", "*"]:
                    for t, s in zip(ts, stars):
                        t["star"], t["suffix"] = (1 if s == "*" else 0), ""
                else:
                    ts[0]["star"], ts[1]["star"] = 0, 1
                    ts[0]["suffix"] = ts[1]["suffix"] = ""
                    notes.append("%s PP%d%s[%d]: star assigned by order, "
                                 "verify against the plates"
                                 % (cid, pp, variety, k))
                ts.sort(key=lambda t: t["star"])
            elif k == 3:
                for i, t in enumerate(ts):
                    t["star"], t["suffix"] = i, ""
                notes.append("%s PP%d%s[3]: %d variants (book shows fewer); "
                             "stars by canonical order"
                             % (cid, pp, variety, len(ts)))
            else:
                # tie-break on a canonical content fingerprint (the cycle
                # structure), never on residual list order
                ts.sort(key=lambda t: [cycle_string(t["cycles"][name])
                                       for name, _ in CHAIM[hm]["gens"]])
                for i, t in enumerate(ts):
                    t["star"], t["suffix"] = 0, "abcdef"[i]
        for t in recs:
            pp, variety = t["pp"], t["variety"]
            star = "*" * t.get("star", 0)
            suff = t.get("suffix", "")
            if k == 1:
                t["label"] = "PP%d%s" % (pp, variety)
                t["anchor"] = "pp%d%s" % (pp, variety.lower())
            elif k <= 3 and gs_sym:
                t["label"] = "PP%d%s[%d]%s%s%s" % (
                    pp, variety, k, subscript(gsub) if gsub else "", star,
                    suff)
                t["anchor"] = "pp%d%s-%d" % (pp, variety.lower(), k)
                if gsub:
                    t["anchor"] += "-" + gsub
                t["anchor"] += "s" * t.get("star", 0)
                if suff:
                    t["anchor"] += suff
            else:
                t["label"] = "PP%d%s[%d]%s%s%s" % (
                    pp, variety, k, subscript(ordinal), star, suff)
                t["anchor"] = "pp%d%s-%d-o%d%s%s" % (
                    pp, variety.lower(), k, ordinal, "s" * t.get("star", 0),
                    suff)
    anchors = [t["anchor"] for t in records]
    assert len(anchors) == len(set(anchors)), "duplicate anchors"
    return notes


# ---------------------------------------------------------------- reference

def load_refs():
    gs_map_path = os.path.join(DOCS, "data", "colored-gs.json")
    with open(gs_map_path, encoding="utf-8") as f:
        gsmap = json.load(f)["groups"]
    ref_path = os.path.join(HERE, "..", "..", "animated-groups", "data",
                            "color-pattern-catalog.json")
    ref2_sigs = {}
    ref3 = None
    try:
        with open(ref_path, encoding="utf-8") as f:
            refd = json.load(f)
        for g in refd["colour_groups"]:
            if g["number_of_colours"] == 2:
                ref2_sigs[g["gs_symbol"]] = g["chaim_short_signature"]
        ref3 = refd
    except FileNotFoundError:
        pass
    return gsmap, ref2_sigs, ref3


def check_against_catalog3(records, gsmap, ref3):
    """Per colour group, the multiset of underlying PP numbers of the
    computed k=3 types must agree with G&S Figs 8.2.3/8.3.6 as recorded in
    color-pattern-catalog.json."""
    if ref3 is None:
        print("  (no sibling catalog; skipping k=3 cross-check)")
        return
    import re
    gs_norm = lambda s: s.replace("_", "")
    cg_by_sym = {}
    for g in ref3["colour_groups"]:
        if g["number_of_colours"] == 3:
            cg_by_sym[g["id"]] = gs_norm(g["gs_symbol"])
    ours_by_sym = {}
    for cid, g in gsmap.items():
        if cid.startswith("c3-"):
            ours_by_sym.setdefault(gs_norm(g["gs"]), []).append(cid)
    book = {}
    for p in ref3["pattern_types"]:
        if p["number_of_colours"] != 3:
            continue
        sym = cg_by_sym[p["colour_group_id"]]
        assert sym in ours_by_sym and len(ours_by_sym[sym]) == 1, sym
        m = re.match(r"PP(\d+)", p["underlying_pattern_type"])
        book.setdefault(ours_by_sym[sym][0], []).append(int(m.group(1)))
    ours = {}
    for t in records:
        if t["k"] == 3:
            ours.setdefault(t["colour_group"], []).append(t["pp"])
    extras = {}
    for cid in sorted(set(book) | set(ours)):
        b = sorted(book.get(cid, []))
        o = sorted(ours.get(cid, []))
        if b != o:
            # every book entry must be among ours (we may have MORE)
            bb = list(b)
            for x in o:
                if x in bb:
                    bb.remove(x)
                else:
                    extras.setdefault(cid, []).append(x)
            assert not bb, ("book type not computed!", cid, bb)
            print("  beyond the book: %s has %s (book %s)" % (cid, o, b))
    n_ours = sum(1 for t in records if t["k"] == 3)
    n_book = sum(1 for p in ref3["pattern_types"]
                 if p["number_of_colours"] == 3)
    print("  k=3 cross-check: computed %d types; G&S Figs 8.2.3/8.3.6 show "
          "%d — the %d extra types (all mirror-edge seats of non-regular "
          "colourings, verified inequivalent by independent brute force) "
          "are missing from the book's figures."
          % (n_ours, n_book, n_ours - n_book))
    return extras


# ------------------------------------------------------------- JSON export

SUMMARY = {
    "p1": "Translations only.", "p2": "Four order-2 cone points.",
    "pm": "Two mirror boundaries.",
    "pg": "Two crosscaps; glide reflections, no mirrors.",
    "cm": "One mirror boundary and one crosscap.",
    "pmm": "Four order-2 mirror corners.",
    "pmg": "Two order-2 cone points and one mirror boundary.",
    "pgg": "Two order-2 cone points and one crosscap.",
    "cmm": "One order-2 cone point and two order-2 mirror corners.",
    "p4": "Order-4, order-4, and order-2 cone points.",
    "p4m": "Order-4, order-4, and order-2 mirror corners.",
    "p4g": "One order-4 cone point and one order-2 mirror corner.",
    "p3": "Three order-3 cone points.",
    "p3m1": "Three order-3 mirror corners.",
    "p31m": "One order-3 cone point and one order-3 mirror corner.",
    "p6": "Order-6, order-3, and order-2 cone points.",
    "p6m": "Order-6, order-3, and order-2 mirror corners.",
}


def chaim_type_string(G, k, sub_orb, kern_orb, normal, sig):
    if k == 1:
        return G.orb
    if k == 2:
        tag = ""
        if G.hm == "pm" and sub_orb == "**":
            tag = {"²*¹*¹": " (1)", "¹*¹*²": " (2)"}.get(sig, "")
        return "%s/%s%s" % (G.orb, sub_orb, tag)
    sup = {2: "²", 3: "³", 4: "⁴", 5: "⁵", 6: "⁶"}[k]
    if normal:
        return "%s%s/%s" % (G.orb, sup, sub_orb)
    return "%s%s//%s" % (G.orb, sup, kern_orb)


def wallpaper_records():
    wall = {}
    for hm in ORDER17:
        G = GROUPS[hm]
        B = view_basis(hm, G.basis)
        gens = []
        for name, el in CHAIM[hm]["gens"]:
            M, v = el
            entry = {"name": name, "geometry": CHAIM[hm]["geometry"][name]}
            if M == I2:
                entry["kind"] = "translation"
                entry["vector"] = list(cart(B, v))
            elif mdet(M) == 1:
                c = EP.rotation_centre(el)
                entry["kind"] = "rotation"
                entry["centre"] = list(cart(B, c))
                entry["order"] = EP.rotation_order(M)
                A = cart_matrix(B, M)
                entry["angle_degrees"] = round(
                    math.degrees(math.atan2(A[1][0], A[0][0])), 6)
            else:
                if EP.is_reflection(el):
                    p0, d = line_of(el)
                    entry["kind"] = "mirror"
                    entry["axis_point"] = list(cart(B, p0))
                    dc = cart(B, d)
                    nrm = math.hypot(*dc)
                    entry["axis_direction"] = [dc[0] / nrm, dc[1] / nrm]
                    entry["glide"] = 0.0
                else:
                    IM = ((1 - M[0][0], -M[0][1]), (-M[1][0], 1 - M[1][1]))
                    if IM[0] != (0, 0):
                        d = (-IM[0][1], IM[0][0])
                    else:
                        d = (-IM[1][1], IM[1][0])
                    dc = cart(B, d)
                    nrm = math.hypot(*dc)
                    dc = (dc[0] / nrm, dc[1] / nrm)
                    vc = cart(B, v)
                    along = vc[0] * dc[0] + vc[1] * dc[1]
                    perp = (vc[0] - along * dc[0], vc[1] - along * dc[1])
                    entry["kind"] = "glide"
                    entry["axis_point"] = [perp[0] / 2, perp[1] / 2]
                    entry["axis_direction"] = list(dc)
                    entry["glide"] = along
            gens.append(entry)
        wall[hm] = {"hm": hm, "orbifold": G.orb, "summary": SUMMARY[hm],
                    "basis": [[B[0][0], B[0][1]], [B[1][0], B[1][1]]],
                    "annotated": CHAIM[hm]["annotated"],
                    "template": CHAIM[hm]["template"],
                    "relations": CHAIM[hm]["relations"],
                    "generators": gens}
    return wall


# ------------------------------------------------------------------- main

def recentre(q, TH):
    """Shift q by a T_H vector to bring it near the origin (T_H-conjugation
    fixes H and the colour classes, so this is a free renderer choice)."""
    t1, t2 = lat_cols(TH)
    best = None
    for i in range(-3, 4):
        for j in range(-3, 4):
            c = (q[0] + i * t1[0] + j * t2[0], q[1] + i * t1[1] + j * t2[1])
            d = float(c[0]) ** 2 + float(c[1]) ** 2
            if best is None or d < best[0]:
                best = (d, c)
    return best[1]


CACHE = os.path.join(HERE, "out", "patterns_k_cache.pkl")


def compute():
    """The slow exact part: colour groups, based-seat orbits, per-type data.
    Cached in enumerate/out/ (delete the pickle to force recompute)."""
    print("colour groups (k <= %d) ..." % KMAX)
    groups = all_colour_groups()
    print("  %d classes (17 trivial + 269)" % len(groups))

    gsmap, ref2_sigs, _ = load_refs()

    strata = {hm: strata_of(hm) for hm in ORDER17}
    moves_cache = {hm: normaliser_moves(GROUPS[hm]) for hm in ORDER17}
    subs_cache = {}

    print("pattern-type orbits (based seats per colour group) ...")
    records = []
    for r in groups:
        hm, k, cid = r["hm"], r["k"], r["id"]
        G = GROUPS[hm]
        st = strata[hm]
        if (hm, k) not in subs_cache:
            subs_cache[(hm, k)] = ([full_group_sub(G)] if k == 1
                                   else subgroups_index_k(G, k))
        index = {s.key: s for s in subs_cache[(hm, k)]}

        # display subgroup: reference-matched for k=2 (SoT Table 11.1
        # signatures), canonical minimum otherwise
        H = index[min(sorted(r["orbit"]))]
        if k == 2:
            sym = gsmap.get(cid, {}).get("gs")
            want = None
            if sym is not None:
                want = ref2_sigs.get(
                    sym.replace("]", "]_") if not sym.endswith("]") else sym)
            if want is not None:
                for kk in sorted(r["orbit"]):
                    sub = index[kk]
                    perms2 = {name: (1 if sub.contains(el) else 2)
                              for name, el in CHAIM[hm]["gens"]}
                    if signature_string(hm, perms2) == want:
                        H = sub
                        break

        TH = translation_stabilizer(H)
        objs = based_objects(G, H, TH, st)
        sgens = stabilizer_generators(H, r["orbit"], index, moves_cache[hm])
        orbs = based_orbits(G, H, TH, st, sgens, objs)

        for orb in orbs:
            sources = set()
            for kk in orb:
                sources |= objs[kk]["strata"]
            slist = sorted(sources,
                           key=lambda i: (ORDER_KIND[st[i]["kind"]],
                                          st[i]["letters"]))
            rep_i = slist[0]
            rep = st[rep_i]
            # re-base so the seat is the stratum's own symbol: H_t = g^-1 H g
            # (S_rep ⊆ H_t since g(rep base) has stabiliser in H)
            gg = None
            for kk in sorted(orb):
                if rep_i in objs[kk]["witnesses"]:
                    gg = objs[kk]["witnesses"][rep_i]
                    break
            assert gg is not None, (cid, "no witness for representative")
            Ht = apply_move(H, mv_inv(gg)) if gg != IDMOVE else H
            assert sub_contains_set(Ht, rep["S"]), (cid, rep["label"])
            letters = set()
            for i in sources:
                letters.update(st[i]["letters"])
            pp, variety = base_pp(hm, rep["stype"], letters)
            reps_c = coset_reps(G, Ht, k)
            cycles = {name: perm_of(G, Ht, reps_c, el)
                      for name, el in CHAIM[hm]["gens"]}
            records.append({
                "hm": hm, "k": k, "colour_group": cid, "rep": rep,
                "sources": [st[i] for i in slist], "pp": pp,
                "variety": variety, "H": Ht, "reps": reps_c,
                "cycles": cycles,
            })
        r["display_H"] = H

    return groups, records


def main():
    build_chaim()
    for hm in ORDER17:
        for name, el in CHAIM[hm]["gens"]:
            assert in_group(GROUPS[hm], el), (hm, name)
        check_relations(hm)

    gsmap, ref2_sigs, ref3 = load_refs()

    if os.path.exists(CACHE):
        with open(CACHE, "rb") as f:
            groups, records = pickle.load(f)
        print("loaded cache %s (%d groups, %d type records)"
              % (CACHE, len(groups), len(records)))
    else:
        groups, records = compute()
        os.makedirs(os.path.dirname(CACHE), exist_ok=True)
        with open(CACHE, "wb") as f:
            pickle.dump((groups, records), f)
        print("cached -> %s" % CACHE)

    per_k = {}
    for t in records:
        per_k[t["k"]] = per_k.get(t["k"], 0) + 1
    print("  types per k:", {k: per_k[k] for k in sorted(per_k)})
    assert per_k[1] == 52, per_k
    assert per_k[2] == 88, per_k

    notes = assign_labels(records, gsmap)
    for n in notes:
        print("  NOTE", n)

    # k=2 regression against the existing catalogue E ids
    old_path = os.path.join(DOCS, "data", "two-color-patterns.json")
    with open(old_path, encoding="utf-8") as f:
        old = json.load(f)
    old_ids = {t["id"] for t in old["types"]}
    new2 = {t["anchor"] for t in records if t["k"] == 2}
    assert new2 == old_ids, ("k=2 anchors changed",
                             sorted(old_ids - new2), sorted(new2 - old_ids))
    print("  k=2 regression: 88/88 anchors identical to "
          "two-color-patterns.json")

    check_against_catalog3(records, gsmap, ref3)

    # ---- assemble JSON
    wall = wallpaper_records()
    ordinal_of = lambda cid: int(cid.split("-")[-1])
    records.sort(key=lambda t: (t["k"], ORDER17.index(t["hm"]),
                                ordinal_of(t["colour_group"]),
                                ORDER_KIND[t["rep"]["kind"]], t["pp"],
                                t["variety"], t.get("star", 0),
                                t.get("suffix", "")))

    types_of = {}
    for t in records:
        types_of.setdefault(t["colour_group"], []).append(t["anchor"])

    out_groups = []
    for r in groups:
        cid = r["id"]
        if cid not in types_of:
            continue
        hm, k = r["hm"], r["k"]
        G = GROUPS[hm]
        H = r["display_H"]
        sub_orb = GROUPS[r["subType"]].orb
        sig = None
        cyc_disp = {}
        if k == 1:
            action, normal, cyclic = "C1", True, True
            kern_orb = sub_orb
            cyc_disp = {name: "1" for name, _ in CHAIM[hm]["gens"]}
        else:
            reps = coset_reps(G, H, k)
            gen_perms = [perm_of(G, H, reps, g) for g in G.full_gens]
            S = perm_group(gen_perms, k)
            action = action_label(S, k)
            normal = (len(S) == k)
            cyclic = normal and action == "C%d" % k
            kern = kernel_sub(G, H, reps, k)
            kern_orb = GROUPS[classify_concrete(as_concrete_group(kern))].orb
            cyc_disp = {name: cycle_string(perm_of(G, H, reps, el))
                        for name, el in CHAIM[hm]["gens"]}
            if k == 2:
                perms2 = {name: (1 if H.contains(el) else 2)
                          for name, el in CHAIM[hm]["gens"]}
                sig = signature_string(hm, perms2)
        gs_sym = gsmap.get(cid, {}).get("gs")
        gs_pretty = None
        if gs_sym:
            gs_pretty = (gs_sym if gs_sym.endswith("]")
                         else gs_sym[:gs_sym.index("]") + 1]
                         + subscript(gs_sym[gs_sym.index("]") + 1:]))
        out_groups.append({
            "id": cid, "k": k, "hm": hm, "orb": G.orb,
            "sub": {"hm": r["subType"], "orb": sub_orb},
            "kernel_orb": kern_orb,
            "action": action, "normal": normal, "cyclic": cyclic,
            "gs": gs_pretty,
            "chaim_type": chaim_type_string(G, k, sub_orb, kern_orb,
                                            normal, sig),
            "cycles": cyc_disp,
            "types": types_of[cid],
        })

    out_types = []
    for t in records:
        hm, k, cid = t["hm"], t["k"], t["colour_group"]
        G = GROUPS[hm]
        B = view_basis(hm, G.basis)
        rep = t["rep"]
        Ht = t["H"]
        seed = seat_point(G, rep)
        seedc = cart(B, seed)
        angle = 0.0
        if rep["stype"].startswith("d"):
            refl = [e for e in rep["S"] if mdet(e[0]) == -1]
            if rep["kind"] == "edge":
                el = refl[0]
            else:
                letter = rep["letters"][0]
                el = dict(CHAIM[hm]["gens"]).get(letter)
                if el is None or el not in rep["S"]:
                    el = refl[0]
            p0, dd = line_of(el)
            dc = cart(B, dd)
            angle = math.degrees(math.atan2(dc[1], dc[0]))
        equiv = [{"kind": s["kind"], "letters": s["letters"],
                  "label": s["label"]} for s in t["sources"]]
        if rep["kind"] == "interior":
            swords = []
        elif rep["kind"] == "corner":
            swords = rep["letters"]
        else:
            swords = [rep["letters"][0]]
        # the marked symbols fix the seat copy's colour A (cycle fixes 0) —
        # for k >= 3 they may still permute the other colours
        # (wrap-around corner partners are conjugate words, not letters)
        for L in swords:
            if L in t["cycles"]:
                assert t["cycles"][L][0] == 0, (t["anchor"], L,
                                                t["cycles"][L])
        mind = min_orbit_distance(G, seed)
        ops = []
        for M, v in G.ops.items():
            A = cart_matrix(B, M)
            ops.append({
                "m": [round(A[0][0], 6), round(A[0][1], 6),
                      round(A[1][0], 6), round(A[1][1], 6)],
                "t": [round(x, 6) for x in cart(B, v)],
                "c": (EC.coset_index(Ht, t["reps"], (M, v))
                      if k > 1 else 0),
            })
        t1p = perm_of(G, Ht, t["reps"], (I2, (F(1), F(0)))) if k > 1 \
            else (0,)
        t2p = perm_of(G, Ht, t["reps"], (I2, (F(0), F(1)))) if k > 1 \
            else (0,)
        out_types.append({
            "id": t["anchor"],
            "label": t["label"],
            "pp": t["pp"], "variety": t["variety"],
            "star": t.get("star", 0),
            "k": k, "hm": hm, "colour_group": cid,
            "primitive": rep["kind"] == "interior",
            "cycles": {name: cycle_string(p)
                       for name, p in t["cycles"].items()},
            "seat": {"kind": rep["kind"], "letters": rep["letters"],
                     "label": rep["label"], "stype": rep["stype"],
                     "order": rep.get("order"),
                     "point": [round(x, 6) for x in seedc],
                     "angle": round(angle, 6),
                     "stab_words": swords, "equivalent": equiv},
            "render": {"ops": ops, "seed": [round(x, 6) for x in seedc],
                       "min_dist": round(mind, 6),
                       "t1": list(t1p), "t2": list(t2p)},
        })

    counts_types = {}
    counts_groups = {}
    for t in out_types:
        counts_types[str(t["k"])] = counts_types.get(str(t["k"]), 0) + 1
    for g in out_groups:
        counts_groups[str(g["k"])] = counts_groups.get(str(g["k"]), 0) + 1
    meta = {
        "title": "Patterns",
        "kmax": KMAX,
        "groups": counts_groups,
        "types": counts_types,
        "total_groups": len(out_groups),
        "total_types": len(out_types),
        "note": "Perfect periodic k-colour pattern types, k <= %d, as marked "
                "coloured orbifolds: colour group (catalogue D id) + based "
                "seat of the motif, up to affine equivalence.  Anchors: G&S "
                "Table 8.2.1 (colour-group counts), the 88 two-colour types "
                "of Figs 8.2.2/8.3.5, the 59 three-colour types of Figs "
                "8.2.3/8.3.6.  Labels for k >= 4 are systematic extensions "
                "(no published tables exist)." % KMAX,
    }
    path = os.path.join(DOCS, "data", "patterns.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump({"meta": meta, "wallpaper": wall, "groups": out_groups,
                   "types": out_types}, f, ensure_ascii=False, indent=1)
    print("wrote %s  (%d groups, %d types)" % (path, len(out_groups),
                                               len(out_types)))
    print("  groups per k:", counts_groups)
    print("  types  per k:", counts_types)


if __name__ == "__main__":
    main()
