#!/usr/bin/env python3
"""Stamp the Monochrome landing and its seventeen family pages from one template.

    python3 docs/monochrome/tools/make-family-pages.py            # write
    python3 docs/monochrome/tools/make-family-pages.py --check    # diff only

Nothing under `docs/monochrome/<family>/` is ever hand-edited: every page
carries a "generated by tools/make-family-pages.py" comment at the top, the
script is idempotent, and `--check` exits 1 naming every page that differs from
a fresh stamp. The node test shells out to `--check`.

Everything that varies between the seventeen pages comes from
`docs/scott-gray/wallpaper-groups.json` and `docs/monochrome/data/monochrome-atlas.json`,
except the one hand-written sentence per family in FAMILY_PROSE below — the
only prose this script owns. The counts are stamped in, so a page reads right
with JavaScript off; `mono-directory.mjs` refreshes the landing's from the live
catalog.
"""
import argparse
import html
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MONO = os.path.dirname(HERE)
DOCS = os.path.dirname(MONO)
VERSION = '20260919-mono-v1'
STAMP = '<!-- generated by tools/make-family-pages.py — do not hand-edit -->'

# The canonical order of the seventeen, which is the order of the landing, the
# pager and every count in the catalog.
ORDER = ['p1', 'p2', 'pm', 'pg', 'cm', 'pmm', 'pmg', 'pgg', 'cmm',
         'p4', 'p4m', 'p4g', 'p3', 'p3m1', 'p31m', 'p6', 'p6m']

# The wallpaper directory has no `scott-gray/p4/`: the p4 card there points at
# `scott-gray/` itself. Monochrome does not copy that wart — `monochrome/p4/`
# exists like the other sixteen — but its "see the field" link must follow it.
FIELD_PAGE = {fam: f'../../scott-gray/{fam}/' for fam in ORDER}
FIELD_PAGE['p4'] = '../../scott-gray/'

# The one hand-written sentence per family. Everything else on the page is
# measured.
FAMILY_PROSE = {
    'p1': 'Only slides, and that is the point: with no point symmetry to lean on, the two colours '
          'are carried onto each other by a half-cell slide or by half a period alone.',
    'p2': 'A half turn about any of four centres. On a two-colour picture the half turn is the '
          'cheapest antisymmetry there is — it needs no symmetry of the wave at all.',
    'pm': 'Parallel mirrors. A colour-reversing mirror pins the contour: w vanishes identically '
          'along the line, so the mirror itself is drawn as a black/white boundary.',
    'pg': 'Parallel glides, and no mirror. A glide has no fixed line, so nothing is forced to '
          'vanish — the thinnest of the seventeen families here, and the one the Weave sits in.',
    'cm': 'Mirrors alternating with glides. Both exchange the inks, so the picture carries two '
          'different kinds of colour-reversing line at once.',
    'pmm': 'A rectangular grid of mirrors with half turns at the crossings. Which of them keep '
           'the colours and which exchange them is the whole content of the table below.',
    'pmg': 'Mirrors one way, glides the other, half turns between them — the family where a '
           'preserved operation and a swapping one sit at right angles.',
    'pgg': 'Glides both ways and half turns, with no mirror at all. Nothing pins the contour, so '
           'these pictures drift rather than fold.',
    'cmm': 'Mirrors both ways with half turns off the crossings: the richest rectangular family, '
           'and the one with the most two-colour rows per picture.',
    'p4': 'Quarter turns. A quarter turn squared is the half turn that exchanges the inks, so on '
          'these fields the quarter turn is what forces black and white to be congruent — this '
          'is the largest family in the catalog.',
    'p4m': 'Quarter turns with mirrors through them. The diagonal mirrors and the axial ones '
           'behave differently under the colour law, and the table says which is which.',
    'p4g': 'Quarter turns with mirrors that miss them — the group of the Weave\'s own still '
           'frame, whose two-colour group is written p4g/p4.',
    'p3': 'Third turns on a triangular lattice. A third turn is not an involution, so the '
          'antisymmetry here comes from a half turn, a mirror or the wait, never from the '
          'threefold centre itself.',
    'p3m1': 'Third turns with mirrors through every centre. On the triangular lattice the mirror '
            'is the operation that exchanges the inks, and its axis is drawn on the picture.',
    'p31m': 'Third turns with mirrors through only some of the centres — the family where two '
            'threefold points of one picture behave differently under the colour law.',
    'p6': 'Sixth turns. The sixth turn cubed is the half turn, so a p6 wave carries a '
          'colour-exchanging half turn about every sixfold centre.',
    'p6m': 'Sixth turns with mirrors: the largest point group of the seventeen, and the one where '
           'most of the operations preserve the inks rather than exchange them.',
}

NAV_GROUPS = [
    ('Background', [
        ('index.html', 'Tutorial'), ('notation.html', 'Notation'),
        ('colourings-tutorial.html', 'Colourings'), ('subgroups-vs-colourings.html', 'Subgroups'),
        ('torus-cayley.html', 'Torus Cayley graphs'), ('hierarchy.html', 'Hierarchy'),
        ('history.html', 'History'),
    ]),
    ('Catalogues', [
        # The design puts the Showcase first under Catalogues, because it is a
        # catalogue and it is the page a reader most wants from anywhere. The
        # other 69 pages of the site gain it when `add-nav.py` runs; these
        # eighteen are stamped with the finished shape.
        ('showcase/', 'Showcase'),
        ('catalog.html', '275 spacetime'), ('wallpaper.html', '275 spacetime (grouped)'),
        ('correspondence.html', '68 colored&lt;&gt;polar crystals'), ('patterns.html', '609 patterns'),
        ('escher.html', '107 Escher'), ('gallery.html', 'Gallery'),
        ('scott-gray-groups.html', 'Reaction–diffusion'),
    ]),
    # Renamed from "Colour": the group is no longer only about colour, and
    # "Colourings" is the word the subject itself uses. `add-nav.py` makes the
    # same rename on the rest of the site.
    ('Colourings', [
        ('colour/', 'Entangled colourings'), ('colour/gyre/', 'Gyre'),
        ('colour/trefoil/', 'Trefoil'), ('monochrome/', 'Monochrome'),
    ]),
    ('Developer', [
        ('reports/', 'Reports'), ('motifs.html', 'Motifs'),
        ('designer.html', 'Designer'), ('billiards.html', 'Billiards'),
    ]),
    ('Superseded', [('crystals-colored.html', '269 coloured crystals')]),
]


def nav(prefix, here):
    """The shared site header, one definition for all eighteen pages.

    `here` is the href (relative to docs/) of the page's own link, which gets
    `class="here"`; `site-header.js` turns that into aria-current="page".
    """
    out = []
    for label, links in NAV_GROUPS:
        classes = ' navgroup-superseded' if label == 'Superseded' else ''
        out.append(f'      <span class="navgroup{classes}">')
        out.append(f'        <span class="navgroup-label">{label}</span>')
        for href, text in links:
            mark = ' class="here"' if href == here else ''
            out.append(f'        <a href="{prefix}{href}"{mark}>{text}</a>')
        out.append('      </span>')
    return '\n'.join(out)


def header(prefix, here):
    return f'''  <header class="site">
  <div class="inner">
    <a class="title" href="{prefix}index.html">Spacetime Groups</a>
    <nav>
{nav(prefix, here)}
    </nav>
  </div>
</header>'''


def load():
    with open(os.path.join(MONO, 'data', 'monochrome-atlas.json'), encoding='utf-8') as fh:
        atlas = json.load(fh)
    with open(os.path.join(DOCS, 'scott-gray', 'wallpaper-groups.json'), encoding='utf-8') as fh:
        groups = json.load(fh)
    return atlas, groups


def thumb_url(entry_id):
    return 'data/thumbs/' + entry_id.replace(':', '-') + '.png'


def best_of(entries):
    """The still a card shows: a featured picture if the family has one, else the
    most legible. Ties break on the id so the stamp is deterministic."""
    return sorted(entries, key=lambda e: (not e['featured'], -e['metrics']['score'], e['id']))[0]


def tier_of(entry):
    """v2 says outright which of the three tiers a reading is in; on v1 the
    working discriminator is the measured half-period law, and the threshold is
    the control by construction."""
    if entry.get('tier') in ('strict', 'broad', 'control'):
        return entry['tier']
    if entry['kind'] == 'threshold':
        return 'control'
    return 'strict' if entry['laws'].get('halfPeriod', [0, 0])[1] == 1 else 'broad'


def family_stats(atlas):
    """Per family: the pictures (distinct fields), the readings by tier, the
    equations, the lattice and the still. Counted the way the explorer counts."""
    fields = atlas['fields']
    stats = {}
    for fam in ORDER:
        here = [e for e in atlas['entries'] if fam in fields[e['field']]['families']]
        keys = sorted({e['field'] for e in here})
        models = {}
        for key in keys:
            models[fields[key]['model']] = models.get(fields[key]['model'], 0) + 1
        gids = sorted({g for key in keys for g in fields[key]['groupIds']
                       if g in FAMILY_GROUPS.get(fam, ())})
        tiers = {t: sum(1 for e in here if tier_of(e) == t) for t in ('strict', 'broad', 'control')}
        lattices = sorted({fields[key]['lattice'] for key in keys})
        stats[fam] = {
            'pictures': len(keys), 'readings': len(here), 'tiers': tiers,
            'strict': tiers['strict'],
            # NOT the tier: the tier says whether s is a symmetry of the field,
            # this says whether the picture is antisymmetric in time, and on the
            # phase-symmetric equations the second is true far more often.
            'halfPeriodExact': sum(1 for e in here
                                   if e['laws'].get('halfPeriod', [0, 0])[1] == 1),
            'groups': gids, 'lattice': lattices[0] if len(lattices) == 1 else 'mixed',
            'models': models, 'entries': here,
        }
    # The seventeen covers have to be seventeen DIFFERENT pictures: a field
    # filed under several families would otherwise be the best-scoring picture
    # of two of them, and ∗333 and ∗632 shipped the same hexagon-and-ring tiling
    # side by side in the directory whose whole job is to tell them apart.
    # Smallest families choose first, because they have the least to choose from.
    taken = set()
    for fam in sorted(ORDER, key=lambda f: len(stats[f]['entries'])):
        here = [e for e in stats[fam]['entries'] if e['id'] not in taken
                and thumb_url(e['id']) not in taken]
        pick = best_of(here or stats[fam]['entries']) if stats[fam]['entries'] else None
        stats[fam]['still'] = thumb_url(pick['id']) if pick else None
        if pick:
            taken.add(thumb_url(pick['id']))
    for fam in ORDER:
        del stats[fam]['entries']
    return stats


FAMILY_GROUPS = {}


def family_page(fam, index, atlas, groups, stats):
    meta = next(f for f in groups['families'] if f['id'] == fam)
    s = stats[fam]
    prev_fam = ORDER[index - 1] if index else None
    next_fam = ORDER[index + 1] if index + 1 < len(ORDER) else None

    def pager_label(other):
        m = next(f for f in groups['families'] if f['id'] == other)
        return f"{html.escape(m['orbifold'].replace('*', '∗'))} {other}"

    prev_link = (f'<a class="family-pager-link family-pager-prev" href="../{prev_fam}/" rel="prev">'
                 f'<span aria-hidden="true">←</span> {pager_label(prev_fam)}</a>') if prev_fam else \
                ('<a class="family-pager-link family-pager-prev" href="../" rel="prev">'
                 '<span aria-hidden="true">←</span> Monochrome</a>')
    next_link = (f'<a class="family-pager-link family-pager-next" href="../{next_fam}/" rel="next">'
                 f'{pager_label(next_fam)} <span aria-hidden="true">→</span></a>') if next_fam else \
                ('<a class="family-pager-link family-pager-next" href="../" rel="next">'
                 'Monochrome <span aria-hidden="true">→</span></a>')
    options = '\n'.join(
        f'<option value="../{other}/"{" selected" if other == fam else ""}>'
        f'{html.escape(next(f for f in groups["families"] if f["id"] == other)["orbifold"].replace("*", "∗"))} · {other}</option>'
        for other in ORDER)
    orbifold = html.escape(meta['orbifold'].replace('*', '∗'))
    lattice = s['lattice']
    equations = ' · '.join(f"{atlas['models'][m]['name']} {n}" for m, n in
                           sorted(s['models'].items(), key=lambda kv: (-kv[1], kv[0])))
    # `tier` is a fact about the involution against the FIELD. Whether waiting
    # half a period also exchanges the inks is a different, measured fact, so
    # it is counted separately here instead of being read off the tier — which
    # is how this sentence used to claim the opposite of the page's own table.
    summary = (f"{html.escape(FAMILY_PROSE[fam])} The catalog holds "
               f"<b>{s['pictures']}</b> saved fields under a {fam} film group, read "
               f"{s['readings']} different ways: <b>{s['tiers']['strict']}</b> where the "
               f"operation <i>s</i> is itself a spacetime symmetry of the wave — so <i>s</i> and "
               f"the half-period wait are two names for one antisymmetry — "
               f"{s['tiers']['broad']} where <i>s</i> is free, and {s['tiers']['control']} "
               f"plain thresholds to compare them with. Separately measured: "
               f"{s['halfPeriodExact']} of the {s['readings']} exchange the two inks after half a "
               f"period exactly.")

    return f'''<!doctype html>
<html lang="en">
{STAMP}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Black-and-white pictures of numerically verified reaction–diffusion waves whose {fam} film groups exchange the two inks: {s['pictures']} pictures, each with its measured two-colour group.">
  <meta name="theme-color" content="#ffffff">
  <title>{orbifold} {fam} — Monochrome — Spacetime Groups</title>
  <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🎞️</text></svg>">
  <link rel="stylesheet" href="../../css/style.css?v=collapsible-header-v1">
  <script defer src="../../js/site-header.js?v=collapsible-header-v1"></script>
  <link rel="stylesheet" href="../../scott-gray/style.css?v=20260907-local-motion">
  <link rel="stylesheet" href="../../scott-gray/wallpaper-style.css?v=20260907-local-motion">
  <link rel="stylesheet" href="../mono-style.css?v={VERSION}">
</head>
<body>
  <a class="skip-link" href="#groups">Skip to the film groups</a>
{header('../../', 'monochrome/')}
  <main class="reaction-diffusion-page mono-page" data-family="{fam}">
    <section class="family-page-header" aria-labelledby="page-title">
      <p class="family-breadcrumb"><a href="../">Monochrome</a> <span aria-hidden="true">·</span> wallpaper group {index + 1} of 17</p>
      <h1 id="page-title"><span class="family-orbifold">{orbifold}</span> <span class="family-hm">{fam}</span></h1>
      <p class="family-summary">{summary}</p>
      <nav class="family-pager" aria-label="Neighbouring wallpaper groups">{prev_link}<a class="family-pager-link family-pager-index" href="../">All 17 wallpaper groups</a>{next_link}<label class="family-select"><span>Go to</span> <select aria-label="Wallpaper group" id="family-nav">
{options}
</select></label></nav>
    </section>

    <h2 class="eyebrow selection-step" id="step-1">1 · The film group</h2>
    <p class="small" id="step-1-note">Each tile is a {fam} film group — the same wallpaper group with a different assignment of time shifts to its operations — and counts the distinct pictures the catalog holds under it. A field filed under more than one film group appears under each.</p>
    <div aria-label="{fam} film groups" class="groups variable-groups" id="groups" role="group"></div>

    <h2 class="eyebrow selection-step" id="step-2">2 · The rule that makes two colours</h2>
    <div class="rule-tiers" id="rule-tiers"></div>
    <div aria-label="Two-colour rule" class="rules" id="rules" role="group"></div>
    <div class="rule-variants" id="rule-variants" hidden><label for="rule-variant" id="rule-variants-label">This rule has more than one reading here:</label> <select id="rule-variant" aria-label="Which reading of this rule"></select></div>
    <p class="rule-law" id="rule-law">Loading catalog…</p>

    <div class="solution-policy"><strong id="policy-label">Loading catalog…</strong><span id="solution-count">…</span>
      <p class="character-note" id="character-note"></p>
    </div>

    <div class="classics">
      <a class="classic" href="../../scott-gray/plume-monochrome/"><img src="../{PLUME_STILL}" alt="" width="52" height="52" loading="lazy" decoding="async"><span><b>Plume Monochrome — “the wave”</b><span>the first of these pictures, on its own endless page · 16 + 16</span></span></a>
      <a class="classic" href="../../scott-gray/weave-monochrome/"><img src="../{WEAVE_STILL}" alt="" width="52" height="52" loading="lazy" decoding="async"><span><b>Weave Monochrome — “the weave”</b><span>the same rule on a woven sibling · 32 + 32</span></span></a>
    </div>

    <noscript><p class="noscript-note">The viewer, the selection ladder and the measured two-colour table are built in the browser, so this page needs JavaScript. Without it, <a href="../">Monochrome</a> still explains the rule, and the standalone <a href="../../scott-gray/plume-monochrome/">Plume</a> and <a href="../../scott-gray/weave-monochrome/">Weave</a> pages each show one picture.</p></noscript>

    <div class="lab">
      <section aria-label="Two-colour animation" class="viewer">
        <div class="image-label viewer-labels"><span id="mode-label">Loading catalog</span><span id="group-label"></span></div>
        <div class="canvas-wrap simulation">
          <canvas aria-label="Black-and-white animation of a verified reaction–diffusion wave. Drag to pan, scroll to zoom, two fingers to turn. Press Space to play or pause." height="768" id="pattern" tabindex="0" width="768"></canvas>
          <svg aria-label="Generator marks over the picture" class="marks-layer" id="marks" viewBox="0 0 768 768" style="display:none"></svg>
          <div id="empty-state"><div class="empty-symbol">∅</div><h2>Loading saved catalog…</h2><p id="empty-description">Parameters, thumbnails and the measured two-colour tables are precomputed.</p><button hidden id="retry-animation" type="button">Retry animation</button></div>
        </div>
        <div class="view-caption"><span class="viewer-hint" id="viewer-hint">Fixed frame — the simulation’s own width</span><span class="scale-label" id="scale-label"></span></div>
        <div class="playback"><button aria-label="Play animation" disabled id="play" type="button">▶ Play</button><button aria-label="Return to first frame" disabled id="rewind" type="button">↤</button><input aria-label="Animation phase" disabled id="phase" max="1" min="0" step="0.001" type="range" value="0"><output id="phase-label">—</output><label>View <select aria-label="View framing" id="framing"><option value="endless">Endless</option><option selected value="simulation">Simulation width</option></select></label><label><span id="tile-label">Width</span> <select aria-label="Simulation width" id="tiles"><option value="1">L</option><option selected value="2">2 L</option><option value="3">3 L</option><option value="4">4 L</option><option value="5">5 L</option><option value="6">6 L</option><option value="7">7 L</option><option value="8">8 L</option></select></label><label>Speed <select aria-label="Playback speed" id="speed"><option value="0.5">Slow</option><option selected value="1">Normal</option><option value="2">Fast</option></select></label></div>
        <div class="overlay-controls"><label><input id="show-marks" type="checkbox"> Generator marks</label><button class="text-button" id="notation-open" type="button" aria-expanded="false" aria-controls="notation">Notation…</button><button class="text-button" id="reset-view" type="button">Reset view</button><button class="text-button" id="fullscreen" type="button">⤢ Fullscreen</button><span id="engine-label">No orbit loaded</span></div>
        <p class="small marks-note">The marks are off on every animation on this site. Tick the box, or press <b>G</b>, to draw the operations of the two-colour group over the picture.</p>
        <div class="notation-panel" hidden id="notation" role="region" aria-label="Reading the generator marks"></div>

        <details class="two-colour" open>
          <summary>The measured two-colour group — <span class="count" id="two-colour-count">…</span></summary>
          <p class="small" id="two-colour-lede"></p>
          <div class="table-scroll"><table>
            <thead><tr><th scope="col">Operation</th><th scope="col">Wait</th><th scope="col">Colours</th><th scope="col">Residual</th></tr></thead>
            <tbody id="two-colour-rows"></tbody>
          </table></div>
          <p class="small" id="two-colour-more"></p>
          <p class="small" id="two-colour-foot"></p>
        </details>

        <details class="numerical-record">
          <summary>Numerical record</summary>
          <p class="caption" id="caption">Only pictures whose two-colour law was re-derived from the saved bytes at every node-frame appear here.</p>
          <div class="metrics" id="metrics"></div>
          <p class="provenance" id="provenance"></p>
        </details>
      </section>

      <aside class="controls">
        <div class="selected"><p class="eyebrow" id="selected-id"></p><h2 id="selected-title"></h2><p id="selected-description"></p></div>
        <section aria-label="Equation, verified parameters and picture selectors" class="atlas-panel">
          <h2 class="eyebrow" id="step-3">3 · Choose the equation</h2>
          <div aria-label="Equation" class="equations" id="equations" role="group"></div>
          <p class="equation-description" id="equation-description"></p>
          <p class="small" id="equation-note"></p>
          <h2 class="eyebrow" id="step-4">4 · Choose verified parameters</h2>
          <label class="atlas-label" for="parameter-set">Saved parameters</label><select disabled id="parameter-set"><option>No verified parameters</option></select>
          <p class="parameter-values" id="parameter-values">Loading precomputed parameters…</p>
          <div class="parameter-map-wrap"><canvas aria-label="Verified parameter plane. Click to select the closest verified parameter set; the selector above also provides keyboard access." height="320" id="parameter-map" tabindex="0" width="660"></canvas><p class="small" id="parameter-map-caption"></p></div>
          <div class="pattern-section"><h2 class="eyebrow" id="step-5">5 · Choose a picture</h2><p class="small" id="pattern-count">Loading saved pictures…</p>
            <div aria-label="Black-and-white thumbnails" class="pattern-thumbnails" id="pattern-thumbnails" role="group"></div>
            <label class="atlas-label" for="solution">Verified two-colour picture</label><select disabled id="solution"><option>No verified pictures</option></select>
          </div>
        </section>
        <label class="stack">Appearance<select id="palette"><option value="mono">Black &amp; white</option><option value="ember">Ember (the wave)</option><option value="concentration">Second channel</option></select></label>
        <label class="stack">Channel<select id="channel"><option value="u">U — the shipped rule</option><option value="v">V — the second channel</option></select></label>
        <p class="small" id="channel-note"></p>
        <p class="small" id="display-range"></p>
        <button class="text-button" disabled id="export" type="button">↓ Export verified picture + evidence</button>
        <p id="status" role="status">Loading the precomputed catalog…</p>
      </aside>
    </div>
    <p class="page-links"><a href="../">All 17 wallpaper groups</a> · <a href="{FIELD_PAGE[fam]}">The same fields in ember ({fam})</a> · <a href="../../scott-gray/weave-monochrome/">Weave Monochrome</a> · <a href="../../scott-gray/plume-monochrome/">Plume Monochrome</a> · <a href="../../colour/">Entangled colourings</a> · <a href="../../scott-gray-groups.html">How the patterns are computed</a></p>
  </main>
  <footer class="site">
    Spacetime groups: the crystallography of looping animations ·
    <a href="https://github.com/yaroslavvb/animated-groups-fable">source</a>
  </footer>
  <script type="module" src="../mono-app.mjs?v={VERSION}"></script>
  <script type="module">
    const select = document.querySelector('#family-nav');
    if (select) select.onchange = () => {{ location.href = select.value; }};
  </script>
</body>
</html>
'''


def landing(atlas, groups, stats):
    cards = []
    for fam in ORDER:
        meta = next(f for f in groups['families'] if f['id'] == fam)
        s = stats[fam]
        orbifold = html.escape(meta['orbifold'].replace('*', '∗'))
        lattice = {'triangular': 'triangular lattice', 'square': 'square lattice'}.get(s['lattice'], 'both lattices')
        cards.append(
            f'        <a class="family-card" data-family="{fam}" href="{fam}/" aria-label="{orbifold}, {fam}: black-and-white pictures">\n'
            f'          <img src="{s["still"]}" width="320" height="320" loading="lazy" decoding="async" alt="">\n'
            f'          <span class="family-card-caption"><strong class="family-card-orbifold">{orbifold}</strong><span class="family-card-hm">{fam}</span></span>\n'
            f'          <span class="family-card-count">{lattice}</span>\n'
            f'          <span class="family-card-results"><span data-picture-count>{s["pictures"]} pictures</span><small data-readings>{s["readings"]} readings · {s["tiers"]["strict"]} where <i>s</i> is a symmetry of the field</small></span>\n'
            f'        </a>')
    total_fields = len(atlas['fields'])
    total_entries = len(atlas['entries'])
    equations = len({atlas['fields'][k]['model'] for k in atlas['fields']})
    by_tier = {t: sum(1 for e in atlas['entries'] if tier_of(e) == t) for t in ('strict', 'broad', 'control')}
    half_exact = sum(1 for e in atlas['entries'] if e['laws'].get('halfPeriod', [0, 0])[1] == 1)
    # The largest residual any shipped reading's drawn-ink claim carries. The
    # page used to say "zero violations", which was not true of the 18 strict
    # entries whose fixed-point samples sit at the float32 noise floor.
    worst_drawn = max((e['laws'].get('strictDrawn', [0, 0])[0] for e in atlas['entries']),
                      default=0.0)
    off_by_a_sample = sum(1 for e in atlas['entries']
                          if e['laws'].get('strictDrawn', [0, 1])[1] == 0)
    return f'''<!doctype html>
<html lang="en">
{STAMP}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Black and white: {total_fields} numerically verified reaction–diffusion waves drawn as two-colour pictures, one rule, seventeen wallpaper groups, every two-colour group measured on the saved bytes.">
  <meta name="theme-color" content="#ffffff">
  <title>Monochrome — Spacetime Groups</title>
  <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🎞️</text></svg>">
  <link rel="stylesheet" href="../css/style.css?v=collapsible-header-v1">
  <script defer src="../js/site-header.js?v=collapsible-header-v1"></script>
  <link rel="stylesheet" href="../css/scott-gray-directory.css?v=20260907-local-motion">
  <link rel="stylesheet" href="mono-style.css?v={VERSION}">
  <script type="module" src="mono-directory.mjs?v={VERSION}"></script>
</head>
<body>
  <a class="skip-link" href="#families">Skip to the wallpaper groups</a>
{header('../', 'monochrome/')}
  <main class="gray-scott-directory mono-directory">
    <section class="directory" aria-labelledby="page-title">
      <p class="overline">Black and white</p>
      <h1 id="page-title">Monochrome</h1>
      <p>Every picture here is the <i>same</i> verified reaction–diffusion wave the catalogue’s <a href="../scott-gray-groups.html">family pages</a> show in ember, drawn by one rule: white where the wave exceeds its own image under a single operation <i>s</i>, black where it falls short. That rule turns a one-colour animation into a proper two-colour spacetime group — and the group is measured on the saved bytes, not asserted.</p>
      <p class="theorem">If some spatial operation <code>s</code> carries the wave onto its own image half a period later, then <code>U(x,t) − U(s x,t)</code> and <code>U(x,t) − U(x, t+T/2)</code> are the <b>same function</b>. So <code>s</code> alone exchanges black and white — by algebra, for any reconstruction filter — half a period alone exchanges them too, and doing both leaves them where they were. Black and white are then congruent by force: their areas are exactly equal.</p>
    </section>

    <section aria-label="The two named pictures">
      <div class="classics">
        <a class="classic" href="../scott-gray/plume-monochrome/"><img src="{PLUME_STILL}" alt="" width="52" height="52" loading="lazy" decoding="async"><span><b>Plume Monochrome — “the wave”</b><span>standalone viewer · endless · its own page · 16 + 16</span></span></a>
        <a class="classic" href="../scott-gray/weave-monochrome/"><img src="{WEAVE_STILL}" alt="" width="52" height="52" loading="lazy" decoding="async"><span><b>Weave Monochrome — “the weave”</b><span>standalone viewer · endless · its own page · 32 + 32</span></span></a>
      </div>
    </section>

    <section id="families" aria-labelledby="families-title">
      <div class="family-directory-heading"><h2 id="families-title">The 17 wallpaper groups</h2><p id="atlas-summary" aria-live="polite">{total_fields} saved fields · {total_entries} readings ({by_tier['strict']} where <i>s</i> is a symmetry of the field) · {equations} equations</p></div>
      <nav class="family-grid" aria-label="Wallpaper groups">
{chr(10).join(cards)}
      </nav>
      <p class="atlas-note">Every two-colour law here was re-derived from the saved float32 bytes at every node-frame, in integer index arithmetic. The swap law <code>w(s x, t) = −w(x, t)</code> is exact by algebra and holds to the last bit; the claims that rest on a measured symmetry of the wave hold to the search’s own residual instead, so on {off_by_a_sample} of the {total_entries} readings the drawn inks disagree at up to {worst_drawn:.2%} of node-frames, where <code>|w|</code> is at the float32 noise floor. A picture is filed under every wallpaper group that hosts its field, so the counts above add up to more than {total_fields}. Of the {total_entries} readings, <b>{by_tier['strict']}</b> are ones where the operation <i>s</i> is itself a spacetime symmetry of the wave — <i>s</i> and the half-period wait are then two names for one antisymmetry, and a field has at most one such picture — {by_tier['broad']} are ones where <i>s</i> is free, and {by_tier['control']} are plain thresholds kept for comparison. Whether the <i>picture</i> is antisymmetric in time is a separate measurement and a commoner one: {half_exact} of the {total_entries} readings exchange the two inks after half a period exactly.</p>
    </section>
  </main>
  <footer class="site">
    Spacetime groups: the crystallography of looping animations ·
    <a href="https://github.com/yaroslavvb/animated-groups-fable">source</a>
  </footer>
</body>
</html>
'''


PLUME_STILL = ''
WEAVE_STILL = ''


def main():
    global PLUME_STILL, WEAVE_STILL, FAMILY_GROUPS
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--check', action='store_true', help='diff against the files on disk and exit 1 on any difference')
    args = ap.parse_args()
    atlas, groups = load()
    if atlas.get('schema') not in ('monochrome-atlas-v1', 'monochrome-atlas-v2'):
        raise SystemExit(f"unsupported catalog schema {atlas.get('schema')}")
    FAMILY_GROUPS = {fam: tuple(g['id'] for g in groups['groups'] if g['family'] == fam) for fam in ORDER}

    # The two named classics name themselves: the builder stamps `shippedPage`
    # on exactly the entries the site already publishes as their own pages.
    # The two named classics name themselves. v2 carries a `classics` block; v1
    # stamps `shippedPage` on the two entries, and the field shas are the last
    # resort so a catalog that drops both still stamps.
    classics = atlas.get('classics') or {}
    shipped = [(str(e.get('shippedPage', {}).get('page', '')), e['id'])
               for e in atlas['entries'] if isinstance(e.get('shippedPage'), dict)]
    def still_for(name, fallback_field):
        for item in classics.values():
            if name in str(item.get('page', '')) and item.get('entry'):
                return thumb_url(item['entry'])
        for page, entry_id in shipped:
            if name in page:
                return thumb_url(entry_id)
        for e in atlas['entries']:
            if e['field'] == fallback_field and e['kind'] == 'half-period':
                return thumb_url(e['id'])
        raise SystemExit(f'no still for {name}')
    PLUME_STILL = still_for('plume', '731aa45654d4')
    WEAVE_STILL = still_for('weave', '459f00246aed')

    stats = family_stats(atlas)
    missing = [fam for fam in ORDER if not stats[fam]['pictures']]
    if missing:
        raise SystemExit(f'the catalog has no pictures for {", ".join(missing)}; refusing to stamp')

    wanted = {os.path.join(MONO, 'index.html'): landing(atlas, groups, stats)}
    for index, fam in enumerate(ORDER):
        wanted[os.path.join(MONO, fam, 'index.html')] = family_page(fam, index, atlas, groups, stats)

    differing = []
    for path, text in sorted(wanted.items()):
        current = None
        if os.path.exists(path):
            with open(path, encoding='utf-8') as fh:
                current = fh.read()
        if current == text:
            continue
        differing.append(os.path.relpath(path, DOCS))
        if not args.check:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, 'w', encoding='utf-8') as fh:
                fh.write(text)
    if args.check:
        if differing:
            print('stale or missing:\n  ' + '\n  '.join(differing))
            return 1
        print(f'{len(wanted)} pages match a fresh stamp')
        return 0
    print(f'{len(wanted)} pages stamped, {len(differing)} changed')
    return 0


if __name__ == '__main__':
    sys.exit(main())
